<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daniel Noone">
<meta name="dcterms.date" content="2025-04-04">

<title>Beer Markets | Hw 3 Post – About</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">About</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../personal_blog.html"> 
<span class="menu-text">Personal Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../danl_310.html"> 
<span class="menu-text">DANL310</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../danl_320.html"> 
<span class="menu-text">DANL320</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#importing-modules-and-data" id="toc-importing-modules-and-data" class="nav-link active" data-scroll-target="#importing-modules-and-data">Importing Modules and Data</a></li>
  <li><a href="#q1" id="toc-q1" class="nav-link" data-scroll-target="#q1">Q1</a></li>
  <li><a href="#q2" id="toc-q2" class="nav-link" data-scroll-target="#q2">Q2</a></li>
  <li><a href="#q3---8" id="toc-q3---8" class="nav-link" data-scroll-target="#q3---8">Q3 - 8</a>
  <ul class="collapse">
  <li><a href="#q3" id="toc-q3" class="nav-link" data-scroll-target="#q3">Q3</a></li>
  <li><a href="#q4" id="toc-q4" class="nav-link" data-scroll-target="#q4">Q4</a>
  <ul class="collapse">
  <li><a href="#model-1" id="toc-model-1" class="nav-link" data-scroll-target="#model-1">Model 1</a></li>
  <li><a href="#model-2" id="toc-model-2" class="nav-link" data-scroll-target="#model-2">Model 2</a></li>
  <li><a href="#model-3" id="toc-model-3" class="nav-link" data-scroll-target="#model-3">Model 3</a></li>
  </ul></li>
  <li><a href="#q5" id="toc-q5" class="nav-link" data-scroll-target="#q5">Q5</a></li>
  <li><a href="#q6" id="toc-q6" class="nav-link" data-scroll-target="#q6">Q6</a></li>
  <li><a href="#q7" id="toc-q7" class="nav-link" data-scroll-target="#q7">Q7</a>
  <ul class="collapse">
  <li><a href="#model-1-1" id="toc-model-1-1" class="nav-link" data-scroll-target="#model-1-1">Model 1</a></li>
  <li><a href="#model-2-1" id="toc-model-2-1" class="nav-link" data-scroll-target="#model-2-1">Model 2</a></li>
  <li><a href="#model-3-1" id="toc-model-3-1" class="nav-link" data-scroll-target="#model-3-1">Model 3</a></li>
  </ul></li>
  <li><a href="#q8" id="toc-q8" class="nav-link" data-scroll-target="#q8">Q8</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Beer Markets | Hw 3 Post</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Homework</div>
    <div class="quarto-category">PySpark</div>
    <div class="quarto-category">Linear Regression</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Daniel Noone </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 4, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="importing-modules-and-data" class="level1">
<h1>Importing Modules and Data</h1>
<div id="cell-2" class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql <span class="im">import</span> SparkSession</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> rand, col, <span class="bu">pow</span>, mean, when, log</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.feature <span class="im">import</span> VectorAssembler</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.regression <span class="im">import</span> LinearRegression</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-3" class="cell" data-outputid="af944a5b-2077-4d91-c225-44fd4e1ac596">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>spark <span class="op">=</span> SparkSession.builder.master(<span class="st">"local[*]"</span>).getOrCreate()</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>beer_markets <span class="op">=</span> pd.read_csv(</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">'https://bcdanl.github.io/data/beer_markets_all_cleaned.csv'</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>bm <span class="op">=</span> spark.createDataFrame(beer_markets)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>bm.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>+---------+--------------------+--------+---------+------------+---------+------------------+--------------------+-----+-------+----------+----------------+---------+--------+--------------+-------------+---+----------+-------+--------------------+------+---------+----------+-------+----------------+-------+
|household|     X_purchase_desc|quantity|    brand|dollar_spent|beer_floz|        price_floz|           container|promo| region|     state|          market|buyertype|  income|childrenUnder6|children6to17|age|employment| degree|          occupation|ethnic|microwave|dishwasher|tvcable|singlefamilyhome|npeople|
+---------+--------------------+--------+---------+------------+---------+------------------+--------------------+-----+-------+----------+----------------+---------+--------+--------------+-------------+---+----------+-------+--------------------+------+---------+----------+-------+----------------+-------+
|  2000946|    BUD LT BR CN 12P|       1|BUD_LIGHT|        8.14|    144.0|0.0565277777777777|                 CAN|false|CENTRAL|  ILLINOIS|  RURAL_ILLINOIS|     male|  20-60k|         false|        false|50+|      none|   Grad|none/retired/student| white|     true|      true|premium|           false|      1|
|  2003036|    BUD LT BR CN 24P|       1|BUD_LIGHT|       17.48|    288.0|0.0606944444444444|                 CAN|false|  SOUTH|   GEORGIA|         ATLANTA|  married|100-200k|         false|        false|50+|      full|College|clerical/sales/se...| white|     true|      true|  basic|            true|      2|
|  2003036|    BUD LT BR CN 24P|       2|BUD_LIGHT|       33.92|    576.0|0.0588888888888888|                 CAN|false|  SOUTH|   GEORGIA|         ATLANTA|  married|100-200k|         false|        false|50+|      full|College|clerical/sales/se...| white|     true|      true|  basic|            true|      2|
|  2003036|    BUD LT BR CN 30P|       2|BUD_LIGHT|       34.74|    720.0|           0.04825|                 CAN|false|  SOUTH|   GEORGIA|         ATLANTA|  married|100-200k|         false|        false|50+|      full|College|clerical/sales/se...| white|     true|      true|  basic|            true|      2|
|  2003036|    BUD LT BR CN 36P|       2|BUD_LIGHT|       40.48|    864.0|0.0468518518518518|                 CAN|false|  SOUTH|   GEORGIA|         ATLANTA|  married|100-200k|         false|        false|50+|      full|College|clerical/sales/se...| white|     true|      true|  basic|            true|      2|
|  2003036|    BUD LT BR CN 36P|       2|BUD_LIGHT|       42.96|    864.0|0.0497222222222222|                 CAN|false|  SOUTH|   GEORGIA|         ATLANTA|  married|100-200k|         false|        false|50+|      full|College|clerical/sales/se...| white|     true|      true|  basic|            true|      2|
|  2003036|    BUD LT BR CN 36P|       2|BUD_LIGHT|       40.96|    864.0|0.0474074074074074|                 CAN|false|  SOUTH|   GEORGIA|         ATLANTA|  married|100-200k|         false|        false|50+|      full|College|clerical/sales/se...| white|     true|      true|  basic|            true|      2|
|  2001521|     BUD LT BR CN 6P|       5|BUD_LIGHT|        30.6|    480.0|           0.06375|                 CAN|false|CENTRAL|   INDIANA|   RURAL_INDIANA|     male| 60-100k|         false|        false|50+|      none|College|none/retired/student| white|     true|      true|   none|           false|      1|
|  2001521|     BUD LT BR CN 6P|       1|BUD_LIGHT|        9.99|     96.0|         0.1040625|                 CAN|false|CENTRAL|   INDIANA|   RURAL_INDIANA|     male| 60-100k|         false|        false|50+|      none|College|none/retired/student| white|     true|      true|   none|           false|      1|
|  2001521|     BUD LT BR CN 6P|       5|BUD_LIGHT|        30.7|    480.0|0.0639583333333333|                 CAN|false|CENTRAL|   INDIANA|   RURAL_INDIANA|     male| 60-100k|         false|        false|50+|      none|College|none/retired/student| white|     true|      true|   none|           false|      1|
|  2001521|     BUD LT BR CN 6P|       3|BUD_LIGHT|       18.36|    288.0|           0.06375|                 CAN|false|CENTRAL|   INDIANA|   RURAL_INDIANA|     male| 60-100k|         false|        false|50+|      none|College|none/retired/student| white|     true|      true|   none|           false|      1|
|  2001521|     BUD LT BR CN 6P|       5|BUD_LIGHT|       31.05|    480.0|         0.0646875|                 CAN|false|CENTRAL|   INDIANA|   RURAL_INDIANA|     male| 60-100k|         false|        false|50+|      none|College|none/retired/student| white|     true|      true|   none|           false|      1|
|  2001521|     BUD LT BR CN 6P|       1|BUD_LIGHT|        9.99|     96.0|         0.1040625|                 CAN|false|CENTRAL|   INDIANA|   RURAL_INDIANA|     male| 60-100k|         false|        false|50+|      none|College|none/retired/student| white|     true|      true|   none|           false|      1|
|  2001978|        BUD LT BR CN|       2|BUD_LIGHT|        2.98|     48.0|0.0620833333333333|                 CAN|false|   EAST|  NEW YORK|        SYRACUSE|  married| 60-100k|         false|        false|50+|      part|     HS|clerical/sales/se...| white|     true|      true|   none|            true|      2|
|  2001978|        BUD LT BR CN|       1|BUD_LIGHT|        1.49|     24.0|0.0620833333333333|                 CAN|false|   EAST|  NEW YORK|        SYRACUSE|  married| 60-100k|         false|        false|50+|      part|     HS|clerical/sales/se...| white|     true|      true|   none|            true|      2|
|  2007716| BUD LT BR NRB LN 6P|       1|BUD_LIGHT|         3.0|     42.0|0.0714285714285714|NON_REFILLABLE_BO...|false|   EAST|NEW JERSEY|    SURBURBAN_NJ|  married|  20-60k|         false|        false|50+|      none|     HS|none/retired/student| white|     true|      true|premium|           false|      2|
|  2007716| BUD LT BR NRB LN 6P|       1|BUD_LIGHT|        4.99|     72.0|0.0693055555555555|NON_REFILLABLE_BO...|false|   EAST|NEW JERSEY|    SURBURBAN_NJ|  married|  20-60k|         false|        false|50+|      none|     HS|none/retired/student| white|     true|      true|premium|           false|      2|
|  2008311|BUD LT BR NRB LN 12P|       1|BUD_LIGHT|        9.99|    144.0|          0.069375|NON_REFILLABLE_BO...| true|  SOUTH|   GEORGIA|         ATLANTA|  married| 60-100k|         false|        false|50+|      full|     HS|                prof| white|     true|      true|   none|            true|      2|
|  2008311|BUD LT BR NRB LN 12P|       1|BUD_LIGHT|        9.49|    144.0|0.0659027777777777|NON_REFILLABLE_BO...| true|  SOUTH|   GEORGIA|         ATLANTA|  married| 60-100k|         false|        false|50+|      full|     HS|                prof| white|     true|      true|   none|            true|      2|
|  2010861|    BUD LT BR CN 24P|       1|BUD_LIGHT|       15.75|    288.0|         0.0546875|                 CAN| true|   WEST|WASHINGTON|RURAL_WASHINGTON|   female|  20-60k|         false|        false|50+|      full|     HS|clerical/sales/se...| white|     true|      true|   none|            true|      1|
+---------+--------------------+--------+---------+------------+---------+------------------+--------------------+-----+-------+----------+----------------+---------+--------+--------------+-------------+---+----------+-------+--------------------+------+---------+----------+-------+----------------+-------+
only showing top 20 rows
</code></pre>
</div>
</div>
</section>
<section id="q1" class="level1">
<h1>Q1</h1>
<div id="cell-5" class="cell" data-outputid="44e132fc-bb5b-4054-e3d5-4d98c4787421">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>bm <span class="op">=</span> (</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    bm</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>((col(<span class="st">"container"</span>) <span class="op">==</span> <span class="st">'CAN'</span>) <span class="op">|</span> (col(<span class="st">'container'</span>) <span class="op">==</span> <span class="st">'NON_REFILLABLE_BOTTLE'</span>))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>bm.groupBy(<span class="st">'container'</span>).count().show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>+--------------------+-----+
|           container|count|
+--------------------+-----+
|NON_REFILLABLE_BO...|19095|
|                 CAN|53015|
+--------------------+-----+
</code></pre>
</div>
</div>
</section>
<section id="q2" class="level1">
<h1>Q2</h1>
<div id="cell-7" class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>dtrain, dtest <span class="op">=</span> bm.randomSplit([<span class="fl">0.67</span>, <span class="fl">0.33</span>], seed <span class="op">=</span> <span class="dv">123</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-8" class="cell" data-outputid="52572c8b-8915-48c8-e2bd-b6db8b565ae8">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>dtrain.describe().show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>+-------+--------------------+--------------------+------------------+-------------+------------------+-----------------+--------------------+--------------------+-------+-------+-------------+---------+--------+-----+----------+-------+--------------------+------+-------+------------------+
|summary|           household|     X_purchase_desc|          quantity|        brand|      dollar_spent|        beer_floz|          price_floz|           container| region|  state|       market|buyertype|  income|  age|employment| degree|          occupation|ethnic|tvcable|           npeople|
+-------+--------------------+--------------------+------------------+-------------+------------------+-----------------+--------------------+--------------------+-------+-------+-------------+---------+--------+-----+----------+-------+--------------------+------+-------+------------------+
|  count|               48375|               48375|             48375|        48375|             48375|            48375|               48375|               48375|  48375|  48375|        48375|    48375|   48375|48375|     48375|  48375|               48375| 48375|  48375|             48375|
|   mean|1.7360907140465118E7|                NULL|1.2943669250645995|         NULL|13.761878656329174|266.0919069767442|0.055713475619634495|                NULL|   NULL|   NULL|         NULL|     NULL|    NULL| NULL|      NULL|   NULL|                NULL|  NULL|   NULL|2.2607670266696056|
| stddev|1.1577801336419007E7|                NULL|0.9830520567722059|         NULL| 8.602034268942313|197.8108831146448|0.013035874225514712|                NULL|   NULL|   NULL|         NULL|     NULL|    NULL| NULL|      NULL|   NULL|                NULL|  NULL|   NULL| 0.878472197275354|
|    min|             2000235|        BUD LT BR CN|                 1|    BUD_LIGHT|0.5099999999999998|             12.0|  0.0013151041666666|                 CAN|CENTRAL|ALABAMA|       ALBANY|   female|100-200k|30-39|      full|College|clerical/sales/se...| asian|  basic|                 1|
|    max|            30440718|NATURAL LT BR NRB...|                30|NATURAL_LIGHT|            147.05|           9216.0|  0.1804166666666666|NON_REFILLABLE_BO...|   WEST|WYOMING|WASHINGTON_DC|  married|under20k|  &lt;30|      part|   none|                prof| white|premium|             5plus|
+-------+--------------------+--------------------+------------------+-------------+------------------+-----------------+--------------------+--------------------+-------+-------+-------------+---------+--------+-----+----------+-------+--------------------+------+-------+------------------+
</code></pre>
</div>
</div>
<div id="cell-9" class="cell" data-outputid="7a13b223-fe98-48a8-8b90-3d7628ae861b">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dtest.describe().show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>+-------+-------------------+--------------------+------------------+-------------+------------------+------------------+--------------------+--------------------+-------+-------+-------------+---------+--------+-----+----------+-------+--------------------+------+-------+------------------+
|summary|          household|     X_purchase_desc|          quantity|        brand|      dollar_spent|         beer_floz|          price_floz|           container| region|  state|       market|buyertype|  income|  age|employment| degree|          occupation|ethnic|tvcable|           npeople|
+-------+-------------------+--------------------+------------------+-------------+------------------+------------------+--------------------+--------------------+-------+-------+-------------+---------+--------+-----+----------+-------+--------------------+------+-------+------------------+
|  count|              23735|               23735|             23735|        23735|             23735|             23735|               23735|               23735|  23735|  23735|        23735|    23735|   23735|23735|     23735|  23735|               23735| 23735|  23735|             23735|
|   mean|1.742943859161576E7|                NULL| 1.297872340425532|         NULL|13.751384874657832| 264.9700442384664|0.055877105905317276|                NULL|   NULL|   NULL|         NULL|     NULL|    NULL| NULL|      NULL|   NULL|                NULL|  NULL|   NULL| 2.251360223031611|
| stddev| 1.15966920346623E7|                NULL|0.9603244653970454|         NULL| 8.536971742556531|188.33659324776673|0.013243025253367981|                NULL|   NULL|   NULL|         NULL|     NULL|    NULL| NULL|      NULL|   NULL|                NULL|  NULL|   NULL|0.8727081906286585|
|    min|            2000417|        BUD LT BR CN|                 1|    BUD_LIGHT|0.5600000000000005|              12.0|  0.0025925925925925|                 CAN|CENTRAL|ALABAMA|       ALBANY|   female|100-200k|30-39|      full|College|clerical/sales/se...| asian|  basic|                 1|
|    max|           30440718|NATURAL LT BR NRB...|                30|NATURAL_LIGHT|            159.13|            4608.0|           0.2340625|NON_REFILLABLE_BO...|   WEST|WYOMING|WASHINGTON_DC|  married|under20k|  &lt;30|      part|   none|                prof| white|premium|             5plus|
+-------+-------------------+--------------------+------------------+-------------+------------------+------------------+--------------------+--------------------+-------+-------+-------------+---------+--------+-----+----------+-------+--------------------+------+-------+------------------+
</code></pre>
</div>
</div>
</section>
<section id="q3---8" class="level1">
<h1>Q3 - 8</h1>
<section id="q3" class="level2">
<h2 class="anchored" data-anchor-id="q3">Q3</h2>
<ul>
<li><strong><em>Model 1</em></strong>
<ul>
<li><p>Uses as features: market, brand, container, and log(beer_floz)</p></li>
<li><p>market, brand, and container are one-hot encoded with <code>BUFFALO-ROCHESTER</code>, <code>BUD_LIGHT</code>, and <code>NON_REFILLABLE_BOTTLE</code> as respective reference levels</p></li>
</ul></li>
<li><strong><em>Model 2</em></strong>
<ul>
<li>Uses the same features as model 1, but with interaction terms between <code>brand</code> and <code>log(beer_floz)</code></li>
</ul></li>
<li><strong><em>Model 3</em></strong>
<ul>
<li>Same features as model 2, but with interaction terms between <code>brand</code> and <code>promo</code>, <code>promo</code> and <code>log(beer_floz)</code>,and a tertiary interaction term between <code>brand</code>, <code>promo</code>, and <code>log(beer_floz)</code></li>
</ul></li>
</ul>
</section>
<section id="q4" class="level2">
<h2 class="anchored" data-anchor-id="q4">Q4</h2>
<div id="cell-14" class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> add_dummy_variables(var_name, reference_level, category_order<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Creates dummy variables for the specified column in the global DataFrames dtrain and dtest.</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Allows manual setting of category order.</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co">        var_name (str): The name of the categorical column (e.g., "borough_name").</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co">        reference_level (int): Index of the category to be used as the reference (dummy omitted).</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co">        category_order (list, optional): List of categories in the desired order. If None, categories are sorted.</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co">        dummy_cols (list): List of dummy column names excluding the reference category.</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="co">        ref_category (str): The category chosen as the reference.</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    <span class="kw">global</span> dtrain, dtest</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Get distinct categories from the training set.</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>    categories <span class="op">=</span> dtrain.select(var_name).distinct().rdd.flatMap(<span class="kw">lambda</span> x: x).collect()</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Convert booleans to strings if present.</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>    categories <span class="op">=</span> [<span class="bu">str</span>(c) <span class="cf">if</span> <span class="bu">isinstance</span>(c, <span class="bu">bool</span>) <span class="cf">else</span> c <span class="cf">for</span> c <span class="kw">in</span> categories]</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Use manual category order if provided; otherwise, sort categories.</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> category_order:</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Ensure all categories are present in the user-defined order</span></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>        missing <span class="op">=</span> <span class="bu">set</span>(categories) <span class="op">-</span> <span class="bu">set</span>(category_order)</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> missing:</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>            <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="ss">f"These categories are missing from your custom order: </span><span class="sc">{</span>missing<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>        categories <span class="op">=</span> category_order</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>        categories <span class="op">=</span> <span class="bu">sorted</span>(categories)</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Validate reference_level</span></span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> reference_level <span class="op">&lt;</span> <span class="dv">0</span> <span class="kw">or</span> reference_level <span class="op">&gt;=</span> <span class="bu">len</span>(categories):</span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="ss">f"reference_level must be between 0 and </span><span class="sc">{</span><span class="bu">len</span>(categories) <span class="op">-</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Define the reference category</span></span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a>    ref_category <span class="op">=</span> categories[reference_level]</span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Reference category (dummy omitted):"</span>, ref_category)</span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create dummy variables for all categories</span></span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> cat <span class="kw">in</span> categories:</span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a>        dummy_col_name <span class="op">=</span> var_name <span class="op">+</span> <span class="st">"_"</span> <span class="op">+</span> <span class="bu">str</span>(cat).replace(<span class="st">" "</span>, <span class="st">"_"</span>)</span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a>        dtrain <span class="op">=</span> dtrain.withColumn(dummy_col_name, when(col(var_name) <span class="op">==</span> cat, <span class="dv">1</span>).otherwise(<span class="dv">0</span>))</span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a>        dtest <span class="op">=</span> dtest.withColumn(dummy_col_name, when(col(var_name) <span class="op">==</span> cat, <span class="dv">1</span>).otherwise(<span class="dv">0</span>))</span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a>    <span class="co"># List of dummy columns, excluding the reference category</span></span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a>    dummy_cols <span class="op">=</span> [var_name <span class="op">+</span> <span class="st">"_"</span> <span class="op">+</span> <span class="bu">str</span>(cat).replace(<span class="st">" "</span>, <span class="st">"_"</span>) <span class="cf">for</span> cat <span class="kw">in</span> categories <span class="cf">if</span> cat <span class="op">!=</span> ref_category]</span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> dummy_cols, ref_category</span>
<span id="cb11-51"><a href="#cb11-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-52"><a href="#cb11-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-53"><a href="#cb11-53" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb11-54"><a href="#cb11-54" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb11-55"><a href="#cb11-55" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tabulate <span class="im">import</span> tabulate</span>
<span id="cb11-56"><a href="#cb11-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-57"><a href="#cb11-57" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> regression_table(model, assembler):</span>
<span id="cb11-58"><a href="#cb11-58" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb11-59"><a href="#cb11-59" aria-hidden="true" tabindex="-1"></a><span class="co">    Creates a formatted regression table from a fitted LinearRegression model and its VectorAssembler,</span></span>
<span id="cb11-60"><a href="#cb11-60" aria-hidden="true" tabindex="-1"></a><span class="co">    and inserts a dashed horizontal line after the Intercept row. The table includes separate columns</span></span>
<span id="cb11-61"><a href="#cb11-61" aria-hidden="true" tabindex="-1"></a><span class="co">    for the 95% confidence interval lower and upper bounds for each coefficient (computed at the 5% significance level)</span></span>
<span id="cb11-62"><a href="#cb11-62" aria-hidden="true" tabindex="-1"></a><span class="co">    and an "Observations" row (using model.summary.numInstances) above the R² row.</span></span>
<span id="cb11-63"><a href="#cb11-63" aria-hidden="true" tabindex="-1"></a><span class="co">    The RMSE row is placed as the last row.</span></span>
<span id="cb11-64"><a href="#cb11-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-65"><a href="#cb11-65" aria-hidden="true" tabindex="-1"></a><span class="co">    The columns are ordered as:</span></span>
<span id="cb11-66"><a href="#cb11-66" aria-hidden="true" tabindex="-1"></a><span class="co">        Metric | Value | Significance | Std. Error | p-value | 95% CI Lower | 95% CI Upper</span></span>
<span id="cb11-67"><a href="#cb11-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-68"><a href="#cb11-68" aria-hidden="true" tabindex="-1"></a><span class="co">    For the "Value", "Std. Error", "95% CI Lower", and "95% CI Upper" columns, commas are inserted every three digits,</span></span>
<span id="cb11-69"><a href="#cb11-69" aria-hidden="true" tabindex="-1"></a><span class="co">    with 3 decimal places (except for Observations which is formatted as an integer with commas).</span></span>
<span id="cb11-70"><a href="#cb11-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-71"><a href="#cb11-71" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb11-72"><a href="#cb11-72" aria-hidden="true" tabindex="-1"></a><span class="co">        model: A fitted LinearRegression model (with a .summary attribute).</span></span>
<span id="cb11-73"><a href="#cb11-73" aria-hidden="true" tabindex="-1"></a><span class="co">        assembler: The VectorAssembler used to assemble the features for the model.</span></span>
<span id="cb11-74"><a href="#cb11-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-75"><a href="#cb11-75" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb11-76"><a href="#cb11-76" aria-hidden="true" tabindex="-1"></a><span class="co">        A formatted string containing the regression table.</span></span>
<span id="cb11-77"><a href="#cb11-77" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb11-78"><a href="#cb11-78" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Extract coefficients and standard errors as NumPy arrays</span></span>
<span id="cb11-79"><a href="#cb11-79" aria-hidden="true" tabindex="-1"></a>    coeffs <span class="op">=</span> model.coefficients.toArray()</span>
<span id="cb11-80"><a href="#cb11-80" aria-hidden="true" tabindex="-1"></a>    std_errors_all <span class="op">=</span> np.array(model.summary.coefficientStandardErrors)</span>
<span id="cb11-81"><a href="#cb11-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-82"><a href="#cb11-82" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Check if the intercept's standard error is included (one extra element)</span></span>
<span id="cb11-83"><a href="#cb11-83" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(std_errors_all) <span class="op">==</span> <span class="bu">len</span>(coeffs) <span class="op">+</span> <span class="dv">1</span>:</span>
<span id="cb11-84"><a href="#cb11-84" aria-hidden="true" tabindex="-1"></a>        intercept_se <span class="op">=</span> std_errors_all[<span class="dv">0</span>]</span>
<span id="cb11-85"><a href="#cb11-85" aria-hidden="true" tabindex="-1"></a>        std_errors <span class="op">=</span> std_errors_all[<span class="dv">1</span>:]</span>
<span id="cb11-86"><a href="#cb11-86" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb11-87"><a href="#cb11-87" aria-hidden="true" tabindex="-1"></a>        intercept_se <span class="op">=</span> <span class="va">None</span></span>
<span id="cb11-88"><a href="#cb11-88" aria-hidden="true" tabindex="-1"></a>        std_errors <span class="op">=</span> std_errors_all</span>
<span id="cb11-89"><a href="#cb11-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-90"><a href="#cb11-90" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute t-statistics for feature coefficients (t = beta / SE(beta))</span></span>
<span id="cb11-91"><a href="#cb11-91" aria-hidden="true" tabindex="-1"></a>    <span class="co"># t_stats = coeffs / std_errors</span></span>
<span id="cb11-92"><a href="#cb11-92" aria-hidden="true" tabindex="-1"></a>    t_stats <span class="op">=</span> model.summary.tValues</span>
<span id="cb11-93"><a href="#cb11-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-94"><a href="#cb11-94" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Degrees of freedom: number of instances minus number of predictors minus 1 (for intercept)</span></span>
<span id="cb11-95"><a href="#cb11-95" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> model.summary.numInstances <span class="op">-</span> <span class="bu">len</span>(coeffs) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb11-96"><a href="#cb11-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-97"><a href="#cb11-97" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute the t-critical value for a 95% confidence interval (two-tailed, 5% significance)</span></span>
<span id="cb11-98"><a href="#cb11-98" aria-hidden="true" tabindex="-1"></a>    t_critical <span class="op">=</span> stats.t.ppf(<span class="fl">0.975</span>, df)</span>
<span id="cb11-99"><a href="#cb11-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-100"><a href="#cb11-100" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute two-tailed p-values for each feature coefficient</span></span>
<span id="cb11-101"><a href="#cb11-101" aria-hidden="true" tabindex="-1"></a>    <span class="co"># p_values = [2 * (1 - stats.t.cdf(np.abs(t), df)) for t in t_stats]</span></span>
<span id="cb11-102"><a href="#cb11-102" aria-hidden="true" tabindex="-1"></a>    p_values <span class="op">=</span> model.summary.pValues</span>
<span id="cb11-103"><a href="#cb11-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-104"><a href="#cb11-104" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Function to assign significance stars based on p-value</span></span>
<span id="cb11-105"><a href="#cb11-105" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> significance_stars(p):</span>
<span id="cb11-106"><a href="#cb11-106" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> p <span class="op">&lt;</span> <span class="fl">0.01</span>:</span>
<span id="cb11-107"><a href="#cb11-107" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="st">"***"</span></span>
<span id="cb11-108"><a href="#cb11-108" aria-hidden="true" tabindex="-1"></a>        <span class="cf">elif</span> p <span class="op">&lt;</span> <span class="fl">0.05</span>:</span>
<span id="cb11-109"><a href="#cb11-109" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="st">"**"</span></span>
<span id="cb11-110"><a href="#cb11-110" aria-hidden="true" tabindex="-1"></a>        <span class="cf">elif</span> p <span class="op">&lt;</span> <span class="fl">0.1</span>:</span>
<span id="cb11-111"><a href="#cb11-111" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="st">"*"</span></span>
<span id="cb11-112"><a href="#cb11-112" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb11-113"><a href="#cb11-113" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="st">""</span></span>
<span id="cb11-114"><a href="#cb11-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-115"><a href="#cb11-115" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Build the table rows.</span></span>
<span id="cb11-116"><a href="#cb11-116" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Order: Metric, Value, Significance, Std. Error, p-value, 95% CI Lower, 95% CI Upper.</span></span>
<span id="cb11-117"><a href="#cb11-117" aria-hidden="true" tabindex="-1"></a>    table <span class="op">=</span> []</span>
<span id="cb11-118"><a href="#cb11-118" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> feature, beta, se, p <span class="kw">in</span> <span class="bu">zip</span>(assembler.getInputCols(), coeffs, std_errors, p_values):</span>
<span id="cb11-119"><a href="#cb11-119" aria-hidden="true" tabindex="-1"></a>        ci_lower <span class="op">=</span> beta <span class="op">-</span> t_critical <span class="op">*</span> se</span>
<span id="cb11-120"><a href="#cb11-120" aria-hidden="true" tabindex="-1"></a>        ci_upper <span class="op">=</span> beta <span class="op">+</span> t_critical <span class="op">*</span> se</span>
<span id="cb11-121"><a href="#cb11-121" aria-hidden="true" tabindex="-1"></a>        table.append([</span>
<span id="cb11-122"><a href="#cb11-122" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Beta: "</span> <span class="op">+</span> feature,       <span class="co"># Metric name</span></span>
<span id="cb11-123"><a href="#cb11-123" aria-hidden="true" tabindex="-1"></a>            beta,                     <span class="co"># Beta estimate (Value)</span></span>
<span id="cb11-124"><a href="#cb11-124" aria-hidden="true" tabindex="-1"></a>            significance_stars(p),    <span class="co"># Significance stars</span></span>
<span id="cb11-125"><a href="#cb11-125" aria-hidden="true" tabindex="-1"></a>            se,                       <span class="co"># Standard error</span></span>
<span id="cb11-126"><a href="#cb11-126" aria-hidden="true" tabindex="-1"></a>            p,                        <span class="co"># p-value</span></span>
<span id="cb11-127"><a href="#cb11-127" aria-hidden="true" tabindex="-1"></a>            ci_lower,                 <span class="co"># 95% CI lower bound</span></span>
<span id="cb11-128"><a href="#cb11-128" aria-hidden="true" tabindex="-1"></a>            ci_upper                  <span class="co"># 95% CI upper bound</span></span>
<span id="cb11-129"><a href="#cb11-129" aria-hidden="true" tabindex="-1"></a>        ])</span>
<span id="cb11-130"><a href="#cb11-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-131"><a href="#cb11-131" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute and add the intercept row with its SE, p-value, significance, and CI (if available)</span></span>
<span id="cb11-132"><a href="#cb11-132" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> intercept_se <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb11-133"><a href="#cb11-133" aria-hidden="true" tabindex="-1"></a>        intercept_t <span class="op">=</span> model.intercept <span class="op">/</span> intercept_se</span>
<span id="cb11-134"><a href="#cb11-134" aria-hidden="true" tabindex="-1"></a>        intercept_p <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> stats.t.cdf(np.<span class="bu">abs</span>(intercept_t), df))</span>
<span id="cb11-135"><a href="#cb11-135" aria-hidden="true" tabindex="-1"></a>        intercept_sig <span class="op">=</span> significance_stars(intercept_p)</span>
<span id="cb11-136"><a href="#cb11-136" aria-hidden="true" tabindex="-1"></a>        ci_intercept_lower <span class="op">=</span> model.intercept <span class="op">-</span> t_critical <span class="op">*</span> intercept_se</span>
<span id="cb11-137"><a href="#cb11-137" aria-hidden="true" tabindex="-1"></a>        ci_intercept_upper <span class="op">=</span> model.intercept <span class="op">+</span> t_critical <span class="op">*</span> intercept_se</span>
<span id="cb11-138"><a href="#cb11-138" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb11-139"><a href="#cb11-139" aria-hidden="true" tabindex="-1"></a>        intercept_se <span class="op">=</span> <span class="st">""</span></span>
<span id="cb11-140"><a href="#cb11-140" aria-hidden="true" tabindex="-1"></a>        intercept_p <span class="op">=</span> <span class="st">""</span></span>
<span id="cb11-141"><a href="#cb11-141" aria-hidden="true" tabindex="-1"></a>        intercept_sig <span class="op">=</span> <span class="st">""</span></span>
<span id="cb11-142"><a href="#cb11-142" aria-hidden="true" tabindex="-1"></a>        ci_intercept_lower <span class="op">=</span> <span class="st">""</span></span>
<span id="cb11-143"><a href="#cb11-143" aria-hidden="true" tabindex="-1"></a>        ci_intercept_upper <span class="op">=</span> <span class="st">""</span></span>
<span id="cb11-144"><a href="#cb11-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-145"><a href="#cb11-145" aria-hidden="true" tabindex="-1"></a>    table.append([</span>
<span id="cb11-146"><a href="#cb11-146" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Intercept"</span>,</span>
<span id="cb11-147"><a href="#cb11-147" aria-hidden="true" tabindex="-1"></a>        model.intercept,</span>
<span id="cb11-148"><a href="#cb11-148" aria-hidden="true" tabindex="-1"></a>        intercept_sig,</span>
<span id="cb11-149"><a href="#cb11-149" aria-hidden="true" tabindex="-1"></a>        intercept_se,</span>
<span id="cb11-150"><a href="#cb11-150" aria-hidden="true" tabindex="-1"></a>        intercept_p,</span>
<span id="cb11-151"><a href="#cb11-151" aria-hidden="true" tabindex="-1"></a>        ci_intercept_lower,</span>
<span id="cb11-152"><a href="#cb11-152" aria-hidden="true" tabindex="-1"></a>        ci_intercept_upper</span>
<span id="cb11-153"><a href="#cb11-153" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb11-154"><a href="#cb11-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-155"><a href="#cb11-155" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Append overall model metrics:</span></span>
<span id="cb11-156"><a href="#cb11-156" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Insert an Observations row using model.summary.numInstances,</span></span>
<span id="cb11-157"><a href="#cb11-157" aria-hidden="true" tabindex="-1"></a>    <span class="co"># then an R² row, and finally the RMSE row as the last row.</span></span>
<span id="cb11-158"><a href="#cb11-158" aria-hidden="true" tabindex="-1"></a>    table.append([<span class="st">"Observations"</span>, model.summary.numInstances, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>])</span>
<span id="cb11-159"><a href="#cb11-159" aria-hidden="true" tabindex="-1"></a>    table.append([<span class="st">"R²"</span>, model.summary.r2, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>])</span>
<span id="cb11-160"><a href="#cb11-160" aria-hidden="true" tabindex="-1"></a>    table.append([<span class="st">"RMSE"</span>, model.summary.rootMeanSquaredError, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>])</span>
<span id="cb11-161"><a href="#cb11-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-162"><a href="#cb11-162" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Format the table.</span></span>
<span id="cb11-163"><a href="#cb11-163" aria-hidden="true" tabindex="-1"></a>    <span class="co"># For the "Value" (index 1), "Std. Error" (index 3), "95% CI Lower" (index 5), and "95% CI Upper" (index 6) columns,</span></span>
<span id="cb11-164"><a href="#cb11-164" aria-hidden="true" tabindex="-1"></a>    <span class="co"># format with commas and 3 decimal places, except for Observations which should be an integer with commas.</span></span>
<span id="cb11-165"><a href="#cb11-165" aria-hidden="true" tabindex="-1"></a>    <span class="co"># For the p-value (index 4), format to 3 decimal places.</span></span>
<span id="cb11-166"><a href="#cb11-166" aria-hidden="true" tabindex="-1"></a>    formatted_table <span class="op">=</span> []</span>
<span id="cb11-167"><a href="#cb11-167" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> row <span class="kw">in</span> table:</span>
<span id="cb11-168"><a href="#cb11-168" aria-hidden="true" tabindex="-1"></a>        formatted_row <span class="op">=</span> []</span>
<span id="cb11-169"><a href="#cb11-169" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i, item <span class="kw">in</span> <span class="bu">enumerate</span>(row):</span>
<span id="cb11-170"><a href="#cb11-170" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> row[<span class="dv">0</span>] <span class="op">==</span> <span class="st">"Observations"</span> <span class="kw">and</span> i <span class="op">==</span> <span class="dv">1</span> <span class="kw">and</span> <span class="bu">isinstance</span>(item, (<span class="bu">int</span>, <span class="bu">float</span>, np.floating)) <span class="kw">and</span> item <span class="op">!=</span> <span class="st">""</span>:</span>
<span id="cb11-171"><a href="#cb11-171" aria-hidden="true" tabindex="-1"></a>                <span class="co"># Format Observations as integer with commas, no decimals.</span></span>
<span id="cb11-172"><a href="#cb11-172" aria-hidden="true" tabindex="-1"></a>                formatted_row.append(<span class="ss">f"</span><span class="sc">{</span><span class="bu">int</span>(item)<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb11-173"><a href="#cb11-173" aria-hidden="true" tabindex="-1"></a>            <span class="cf">elif</span> <span class="bu">isinstance</span>(item, (<span class="bu">int</span>, <span class="bu">float</span>, np.floating)) <span class="kw">and</span> item <span class="op">!=</span> <span class="st">""</span>:</span>
<span id="cb11-174"><a href="#cb11-174" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> i <span class="kw">in</span> [<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">6</span>]:</span>
<span id="cb11-175"><a href="#cb11-175" aria-hidden="true" tabindex="-1"></a>                    formatted_row.append(<span class="ss">f"</span><span class="sc">{</span>item<span class="sc">:,.3f}</span><span class="ss">"</span>)</span>
<span id="cb11-176"><a href="#cb11-176" aria-hidden="true" tabindex="-1"></a>                <span class="cf">elif</span> i <span class="op">==</span> <span class="dv">4</span>:</span>
<span id="cb11-177"><a href="#cb11-177" aria-hidden="true" tabindex="-1"></a>                    formatted_row.append(<span class="ss">f"</span><span class="sc">{</span>item<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb11-178"><a href="#cb11-178" aria-hidden="true" tabindex="-1"></a>                <span class="cf">else</span>:</span>
<span id="cb11-179"><a href="#cb11-179" aria-hidden="true" tabindex="-1"></a>                    formatted_row.append(<span class="ss">f"</span><span class="sc">{</span>item<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb11-180"><a href="#cb11-180" aria-hidden="true" tabindex="-1"></a>            <span class="cf">else</span>:</span>
<span id="cb11-181"><a href="#cb11-181" aria-hidden="true" tabindex="-1"></a>                formatted_row.append(item)</span>
<span id="cb11-182"><a href="#cb11-182" aria-hidden="true" tabindex="-1"></a>        formatted_table.append(formatted_row)</span>
<span id="cb11-183"><a href="#cb11-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-184"><a href="#cb11-184" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Generate the table string using tabulate.</span></span>
<span id="cb11-185"><a href="#cb11-185" aria-hidden="true" tabindex="-1"></a>    table_str <span class="op">=</span> tabulate(</span>
<span id="cb11-186"><a href="#cb11-186" aria-hidden="true" tabindex="-1"></a>        formatted_table,</span>
<span id="cb11-187"><a href="#cb11-187" aria-hidden="true" tabindex="-1"></a>        headers<span class="op">=</span>[<span class="st">"Metric"</span>, <span class="st">"Value"</span>, <span class="st">"Sig."</span>, <span class="st">"Std. Error"</span>, <span class="st">"p-value"</span>, <span class="st">"95% CI Lower"</span>, <span class="st">"95% CI Upper"</span>],</span>
<span id="cb11-188"><a href="#cb11-188" aria-hidden="true" tabindex="-1"></a>        tablefmt<span class="op">=</span><span class="st">"pretty"</span>,</span>
<span id="cb11-189"><a href="#cb11-189" aria-hidden="true" tabindex="-1"></a>        colalign<span class="op">=</span>(<span class="st">"left"</span>, <span class="st">"right"</span>, <span class="st">"center"</span>, <span class="st">"right"</span>, <span class="st">"right"</span>, <span class="st">"right"</span>, <span class="st">"right"</span>)</span>
<span id="cb11-190"><a href="#cb11-190" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb11-191"><a href="#cb11-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-192"><a href="#cb11-192" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Insert a dashed line after the Intercept row for clarity.</span></span>
<span id="cb11-193"><a href="#cb11-193" aria-hidden="true" tabindex="-1"></a>    lines <span class="op">=</span> table_str.split(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb11-194"><a href="#cb11-194" aria-hidden="true" tabindex="-1"></a>    dash_line <span class="op">=</span> <span class="st">'-'</span> <span class="op">*</span> <span class="bu">len</span>(lines[<span class="dv">0</span>])</span>
<span id="cb11-195"><a href="#cb11-195" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, line <span class="kw">in</span> <span class="bu">enumerate</span>(lines):</span>
<span id="cb11-196"><a href="#cb11-196" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="st">"Intercept"</span> <span class="kw">in</span> line <span class="kw">and</span> <span class="kw">not</span> line.strip().startswith(<span class="st">'+'</span>):</span>
<span id="cb11-197"><a href="#cb11-197" aria-hidden="true" tabindex="-1"></a>            lines.insert(i<span class="op">+</span><span class="dv">1</span>, dash_line)</span>
<span id="cb11-198"><a href="#cb11-198" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb11-199"><a href="#cb11-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-200"><a href="#cb11-200" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>.join(lines)</span>
<span id="cb11-201"><a href="#cb11-201" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="model-1" class="level3">
<h3 class="anchored" data-anchor-id="model-1">Model 1</h3>
<ul>
<li>market (dummys), brand (dummys), container (CAN not as ref lev), log(beer_floz)</li>
</ul>
<div id="cell-16" class="cell" data-outputid="5a76a863-f3db-44a8-d9d6-8f8609735e9b">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>dtrain <span class="op">=</span> dtrain.withColumn(<span class="st">'log_floz'</span>, log(<span class="st">'beer_floz'</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>dtrain <span class="op">=</span> dtrain.withColumn(<span class="st">'log_price_floz'</span>, log(<span class="st">'price_floz'</span>))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>dtest <span class="op">=</span> dtest.withColumn(<span class="st">'log_floz'</span>, log(<span class="st">'beer_floz'</span>))</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>dtest <span class="op">=</span> dtest.withColumn(<span class="st">'log_price_floz'</span>, log(<span class="st">'price_floz'</span>))</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>dtest.orderBy(<span class="st">'market'</span>, <span class="st">'brand'</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>dtrain.orderBy(<span class="st">'market'</span>, <span class="st">'brand'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="60">
<pre><code>DataFrame[household: bigint, X_purchase_desc: string, quantity: bigint, brand: string, dollar_spent: double, beer_floz: double, price_floz: double, container: string, promo: boolean, region: string, state: string, market: string, buyertype: string, income: string, childrenUnder6: boolean, children6to17: boolean, age: string, employment: string, degree: string, occupation: string, ethnic: string, microwave: boolean, dishwasher: boolean, tvcable: string, singlefamilyhome: boolean, npeople: string, log_floz: double, log_price_floz: double, market_ALBANY: int, market_ATLANTA: int, market_BALTIMORE: int, market_BIRMINGHAM: int, market_BOSTON: int, market_BUFFALO-ROCHESTER: int, market_CHARLOTTE: int, market_CHICAGO: int, market_CINCINNATI: int, market_CLEVELAND: int, market_COLUMBUS: int, market_DALLAS: int, market_DENVER: int, market_DES_MOINES: int, market_DETROIT: int, market_EXURBAN_NJ: int, market_EXURBAN_NY: int, market_GRAND_RAPIDS: int, market_HARTFORD-NEW_HAVEN: int, market_HOUSTON: int, market_INDIANAPOLIS: int, market_JACKSONVILLE: int, market_KANSAS_CITY: int, market_LITTLE_ROCK: int, market_LOS_ANGELES: int, market_LOUISVILLE: int, market_MEMPHIS: int, market_MIAMI: int, market_MILWAUKEE: int, market_MINNEAPOLIS: int, market_NASHVILLE: int, market_NEW_ORLEANS-MOBILE: int, market_OKLAHOMA_CITY-TULSA: int, market_OMAHA: int, market_ORLANDO: int, market_PHILADELPHIA: int, market_PHOENIX: int, market_PITTSBURGH: int, market_PORTLAND: int, market_RALEIGH-DURHAM: int, market_RICHMOND: int, market_RURAL_ALABAMA: int, market_RURAL_ARKANSAS: int, market_RURAL_CALIFORNIA: int, market_RURAL_COLORADO: int, market_RURAL_FLORIDA: int, market_RURAL_GEORGIA: int, market_RURAL_IDAHO: int, market_RURAL_ILLINOIS: int, market_RURAL_INDIANA: int, market_RURAL_IOWA: int, market_RURAL_KANSAS: int, market_RURAL_KENTUCKY: int, market_RURAL_LOUISIANA: int, market_RURAL_MAINE: int, market_RURAL_MICHIGAN: int, market_RURAL_MINNESOTA: int, market_RURAL_MISSISSIPPI: int, market_RURAL_MISSOURI: int, market_RURAL_MONTANA: int, market_RURAL_NEBRASKA: int, market_RURAL_NEVADA: int, market_RURAL_NEW_HAMPSHIRE: int, market_RURAL_NEW_MEXICO: int, market_RURAL_NEW_YORK: int, market_RURAL_NORTH_CAROLINA: int, market_RURAL_NORTH_DAKOTA: int, market_RURAL_OHIO: int, market_RURAL_OKLAHOMA: int, market_RURAL_OREGON: int, market_RURAL_PENNSYLVANIA: int, market_RURAL_SOUTH_CAROLINA: int, market_RURAL_SOUTH_DAKOTA: int, market_RURAL_TENNESSEE: int, market_RURAL_TEXAS: int, market_RURAL_VERMONT: int, market_RURAL_VIRGINIA: int, market_RURAL_WASHINGTON: int, market_RURAL_WEST_VIRGINIA: int, market_RURAL_WISCONSIN: int, market_RURAL_WYOMING: int, market_SACRAMENTO: int, market_SALT_LAKE_CITY: int, market_SAN_ANTONIO: int, market_SAN_DIEGO: int, market_SAN_FRANCISCO: int, market_SEATTLE: int, market_ST_LOUIS: int, market_SURBURBAN_NJ: int, market_SURBURBAN_NY: int, market_SYRACUSE: int, market_TAMPA: int, market_URBAN_NY: int, market_WASHINGTON_DC: int, brand_BUD_LIGHT: int, brand_BUSCH_LIGHT: int, brand_COORS_LIGHT: int, brand_MILLER_LITE: int, brand_NATURAL_LIGHT: int, container_CAN: int, container_NON_REFILLABLE_BOTTLE: int]</code></pre>
</div>
</div>
<div id="cell-17" class="cell" data-outputid="ae944dd2-a7ab-4a29-f579-174b4a30069d">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>market_dummys, market_reflev <span class="op">=</span> add_dummy_variables(<span class="st">'market'</span>, reference_level<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>brand_dummys, brand_reflev <span class="op">=</span> add_dummy_variables(<span class="st">'brand'</span>, reference_level<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>container_dummys, container_reflev <span class="op">=</span> add_dummy_variables(<span class="st">'container'</span>, reference_level<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>cont <span class="op">=</span> [<span class="st">'log_floz'</span>]</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>features_1 <span class="op">=</span> market_dummys <span class="op">+</span> brand_dummys <span class="op">+</span> container_dummys <span class="op">+</span> cont</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reference category (dummy omitted): BUFFALO-ROCHESTER
Reference category (dummy omitted): BUD_LIGHT
Reference category (dummy omitted): NON_REFILLABLE_BOTTLE</code></pre>
</div>
</div>
<div id="cell-18" class="cell" data-outputid="f63b4bd6-1745-405a-e6ce-30a56e2494e0">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>assembler1 <span class="op">=</span> VectorAssembler(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    inputCols <span class="op">=</span> features_1,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    outputCol<span class="op">=</span><span class="st">'features'</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>dtrain1 <span class="op">=</span> assembler1.transform(dtrain)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>dtest1  <span class="op">=</span> assembler1.transform(dtest)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>model1 <span class="op">=</span> LinearRegression(</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    featuresCol<span class="op">=</span><span class="st">'features'</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    labelCol<span class="op">=</span><span class="st">'log_price_floz'</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>).fit(dtrain1)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>dtest1 <span class="op">=</span> model1.transform(dtest1)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(regression_table(model1, assembler1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>+-----------------------------------+--------+------+------------+---------+--------------+--------------+
| Metric                            |  Value | Sig. | Std. Error | p-value | 95% CI Lower | 95% CI Upper |
+-----------------------------------+--------+------+------------+---------+--------------+--------------+
| Beta: market_ALBANY               |  0.031 |  **  |      0.010 |   0.013 |        0.011 |        0.051 |
| Beta: market_ATLANTA              |  0.095 | ***  |      0.014 |   0.000 |        0.068 |        0.122 |
| Beta: market_BALTIMORE            |  0.099 | ***  |      0.010 |   0.000 |        0.079 |        0.119 |
| Beta: market_BIRMINGHAM           |  0.128 | ***  |      0.011 |   0.000 |        0.107 |        0.149 |
| Beta: market_BOSTON               |  0.129 | ***  |      0.010 |   0.000 |        0.109 |        0.149 |
| Beta: market_CHARLOTTE            |  0.033 | ***  |      0.010 |   0.001 |        0.014 |        0.052 |
| Beta: market_CHICAGO              | -0.003 |      |      0.010 |   0.775 |       -0.023 |        0.017 |
| Beta: market_CINCINNATI           |  0.088 | ***  |      0.010 |   0.000 |        0.068 |        0.108 |
| Beta: market_CLEVELAND            |  0.070 | ***  |      0.010 |   0.000 |        0.051 |        0.089 |
| Beta: market_COLUMBUS             |  0.077 | ***  |      0.010 |   0.000 |        0.058 |        0.096 |
| Beta: market_DALLAS               |  0.210 | ***  |      0.011 |   0.000 |        0.188 |        0.232 |
| Beta: market_DENVER               |  0.124 | ***  |      0.011 |   0.000 |        0.101 |        0.147 |
| Beta: market_DES_MOINES           |  0.141 | ***  |      0.010 |   0.000 |        0.122 |        0.160 |
| Beta: market_DETROIT              |  0.096 | ***  |      0.016 |   0.000 |        0.065 |        0.127 |
| Beta: market_EXURBAN_NJ           |  0.224 | ***  |      0.021 |   0.000 |        0.182 |        0.265 |
| Beta: market_EXURBAN_NY           |  0.137 | ***  |      0.011 |   0.000 |        0.115 |        0.159 |
| Beta: market_GRAND_RAPIDS         |  0.087 | ***  |      0.014 |   0.000 |        0.061 |        0.114 |
| Beta: market_HARTFORD-NEW_HAVEN   |  0.150 | ***  |      0.010 |   0.000 |        0.131 |        0.169 |
| Beta: market_HOUSTON              |  0.122 | ***  |      0.010 |   0.000 |        0.102 |        0.142 |
| Beta: market_INDIANAPOLIS         |  0.052 | ***  |      0.012 |   0.000 |        0.028 |        0.076 |
| Beta: market_JACKSONVILLE         |  0.128 | ***  |      0.012 |   0.000 |        0.106 |        0.151 |
| Beta: market_KANSAS_CITY          |  0.083 | ***  |      0.013 |   0.000 |        0.058 |        0.109 |
| Beta: market_LITTLE_ROCK          |  0.108 | ***  |      0.010 |   0.000 |        0.089 |        0.127 |
| Beta: market_LOS_ANGELES          |  0.033 | ***  |      0.011 |   0.001 |        0.011 |        0.055 |
| Beta: market_LOUISVILLE           |  0.070 | ***  |      0.012 |   0.000 |        0.046 |        0.094 |
| Beta: market_MEMPHIS              |  0.129 | ***  |      0.009 |   0.000 |        0.111 |        0.147 |
| Beta: market_MIAMI                |  0.115 | ***  |      0.011 |   0.000 |        0.093 |        0.137 |
| Beta: market_MILWAUKEE            |  0.039 | ***  |      0.011 |   0.001 |        0.017 |        0.061 |
| Beta: market_MINNEAPOLIS          |  0.135 | ***  |      0.011 |   0.000 |        0.114 |        0.156 |
| Beta: market_NASHVILLE            |  0.147 | ***  |      0.011 |   0.000 |        0.126 |        0.169 |
| Beta: market_NEW_ORLEANS-MOBILE   |  0.137 | ***  |      0.011 |   0.000 |        0.115 |        0.159 |
| Beta: market_OKLAHOMA_CITY-TULSA  |  0.150 | ***  |      0.011 |   0.000 |        0.129 |        0.171 |
| Beta: market_OMAHA                |  0.130 | ***  |      0.010 |   0.000 |        0.109 |        0.150 |
| Beta: market_ORLANDO              |  0.108 | ***  |      0.013 |   0.000 |        0.083 |        0.134 |
| Beta: market_PHILADELPHIA         |  0.124 | ***  |      0.009 |   0.000 |        0.106 |        0.143 |
| Beta: market_PHOENIX              |  0.145 | ***  |      0.014 |   0.000 |        0.118 |        0.173 |
| Beta: market_PITTSBURGH           |  0.099 | ***  |      0.012 |   0.000 |        0.076 |        0.123 |
| Beta: market_PORTLAND             |  0.109 | ***  |      0.010 |   0.000 |        0.089 |        0.130 |
| Beta: market_RALEIGH-DURHAM       |  0.087 | ***  |      0.011 |   0.000 |        0.066 |        0.107 |
| Beta: market_RICHMOND             |  0.044 | ***  |      0.014 |   0.000 |        0.016 |        0.072 |
| Beta: market_RURAL_ALABAMA        |  0.164 | ***  |      0.018 |   0.000 |        0.128 |        0.200 |
| Beta: market_RURAL_ARKANSAS       |  0.189 | ***  |      0.011 |   0.000 |        0.167 |        0.210 |
| Beta: market_RURAL_CALIFORNIA     |  0.048 | ***  |      0.047 |   0.000 |       -0.045 |        0.140 |
| Beta: market_RURAL_COLORADO       |  0.199 | ***  |      0.012 |   0.000 |        0.175 |        0.223 |
| Beta: market_RURAL_FLORIDA        |  0.070 | ***  |      0.013 |   0.000 |        0.045 |        0.095 |
| Beta: market_RURAL_GEORGIA        |  0.138 | ***  |      0.019 |   0.000 |        0.101 |        0.175 |
| Beta: market_RURAL_IDAHO          |  0.146 | ***  |      0.010 |   0.000 |        0.126 |        0.166 |
| Beta: market_RURAL_ILLINOIS       |  0.018 |  *   |      0.013 |   0.073 |       -0.006 |        0.043 |
| Beta: market_RURAL_INDIANA        |  0.070 | ***  |      0.011 |   0.000 |        0.049 |        0.091 |
| Beta: market_RURAL_IOWA           |  0.061 | ***  |      0.018 |   0.000 |        0.025 |        0.096 |
| Beta: market_RURAL_KANSAS         |  0.140 | ***  |      0.017 |   0.000 |        0.108 |        0.173 |
| Beta: market_RURAL_KENTUCKY       |  0.152 | ***  |      0.013 |   0.000 |        0.126 |        0.178 |
| Beta: market_RURAL_LOUISIANA      |  0.079 | ***  |      0.014 |   0.000 |        0.052 |        0.106 |
| Beta: market_RURAL_MAINE          |  0.090 | ***  |      0.011 |   0.000 |        0.068 |        0.112 |
| Beta: market_RURAL_MICHIGAN       |  0.089 | ***  |      0.019 |   0.000 |        0.051 |        0.126 |
| Beta: market_RURAL_MINNESOTA      |  0.176 | ***  |      0.014 |   0.000 |        0.149 |        0.203 |
| Beta: market_RURAL_MISSISSIPPI    |  0.053 | ***  |      0.012 |   0.000 |        0.030 |        0.076 |
| Beta: market_RURAL_MISSOURI       |  0.110 | ***  |      0.014 |   0.000 |        0.084 |        0.137 |
| Beta: market_RURAL_MONTANA        |  0.130 | ***  |      0.022 |   0.000 |        0.087 |        0.172 |
| Beta: market_RURAL_NEBRASKA       |  0.148 | ***  |      0.012 |   0.000 |        0.125 |        0.172 |
| Beta: market_RURAL_NEVADA         |  0.046 | ***  |      0.040 |   0.000 |       -0.033 |        0.126 |
| Beta: market_RURAL_NEW_HAMPSHIRE  |  0.070 |  *   |      0.013 |   0.085 |        0.044 |        0.096 |
| Beta: market_RURAL_NEW_MEXICO     |  0.168 | ***  |      0.064 |   0.000 |        0.042 |        0.293 |
| Beta: market_RURAL_NEW_YORK       | -0.007 |      |      0.011 |   0.919 |       -0.028 |        0.015 |
| Beta: market_RURAL_NORTH_CAROLINA |  0.027 |  **  |      0.020 |   0.016 |       -0.012 |        0.065 |
| Beta: market_RURAL_NORTH_DAKOTA   |  0.245 | ***  |      0.016 |   0.000 |        0.214 |        0.276 |
| Beta: market_RURAL_OHIO           |  0.095 | ***  |      0.029 |   0.000 |        0.038 |        0.151 |
| Beta: market_RURAL_OKLAHOMA       |  0.158 | ***  |      0.037 |   0.000 |        0.086 |        0.230 |
| Beta: market_RURAL_OREGON         |  0.007 |      |      0.014 |   0.853 |       -0.022 |        0.035 |
| Beta: market_RURAL_PENNSYLVANIA   |  0.136 | ***  |      0.010 |   0.000 |        0.116 |        0.156 |
| Beta: market_RURAL_SOUTH_CAROLINA |  0.057 | ***  |      0.019 |   0.000 |        0.020 |        0.093 |
| Beta: market_RURAL_SOUTH_DAKOTA   |  0.085 | ***  |      0.013 |   0.000 |        0.060 |        0.111 |
| Beta: market_RURAL_TENNESSEE      |  0.175 | ***  |      0.010 |   0.000 |        0.156 |        0.195 |
| Beta: market_RURAL_TEXAS          |  0.178 | ***  |      0.020 |   0.000 |        0.139 |        0.216 |
| Beta: market_RURAL_VERMONT        |  0.090 | ***  |      0.017 |   0.000 |        0.057 |        0.124 |
| Beta: market_RURAL_VIRGINIA       |  0.017 |      |      0.014 |   0.315 |       -0.010 |        0.045 |
| Beta: market_RURAL_WASHINGTON     |  0.100 | ***  |      0.015 |   0.000 |        0.071 |        0.130 |
| Beta: market_RURAL_WEST_VIRGINIA  | -0.033 |  **  |      0.010 |   0.030 |       -0.053 |       -0.013 |
| Beta: market_RURAL_WISCONSIN      |  0.049 | ***  |      0.033 |   0.000 |       -0.016 |        0.115 |
| Beta: market_RURAL_WYOMING        |  0.153 | ***  |      0.011 |   0.000 |        0.132 |        0.174 |
| Beta: market_SACRAMENTO           |  0.032 | ***  |      0.014 |   0.003 |        0.004 |        0.060 |
| Beta: market_SALT_LAKE_CITY       |  0.120 | ***  |      0.009 |   0.000 |        0.101 |        0.138 |
| Beta: market_SAN_ANTONIO          |  0.146 | ***  |      0.012 |   0.000 |        0.123 |        0.168 |
| Beta: market_SAN_DIEGO            |  0.018 |      |      0.011 |   0.114 |       -0.003 |        0.040 |
| Beta: market_SAN_FRANCISCO        |  0.080 | ***  |      0.011 |   0.000 |        0.058 |        0.101 |
| Beta: market_SEATTLE              |  0.114 | ***  |      0.010 |   0.000 |        0.094 |        0.134 |
| Beta: market_ST_LOUIS             |  0.042 | ***  |      0.013 |   0.000 |        0.017 |        0.068 |
| Beta: market_SURBURBAN_NJ         | -0.018 |      |      0.013 |   0.168 |       -0.043 |        0.007 |
| Beta: market_SURBURBAN_NY         |  0.107 | ***  |      0.014 |   0.000 |        0.079 |        0.135 |
| Beta: market_SYRACUSE             | -0.032 |  **  |      0.009 |   0.026 |       -0.050 |       -0.014 |
| Beta: market_TAMPA                |  0.112 | ***  |      0.011 |   0.000 |        0.090 |        0.134 |
| Beta: market_URBAN_NY             |  0.172 | ***  |      0.011 |   0.000 |        0.151 |        0.194 |
| Beta: market_WASHINGTON_DC        |  0.108 | ***  |      0.003 |   0.000 |        0.102 |        0.113 |
| Beta: brand_BUSCH_LIGHT           | -0.260 | ***  |      0.002 |   0.000 |       -0.264 |       -0.255 |
| Beta: brand_COORS_LIGHT           | -0.002 |      |      0.002 |   0.408 |       -0.006 |        0.002 |
| Beta: brand_MILLER_LITE           | -0.013 | ***  |      0.002 |   0.000 |       -0.018 |       -0.008 |
| Beta: brand_NATURAL_LIGHT         | -0.318 | ***  |      0.002 |   0.000 |       -0.322 |       -0.314 |
| Beta: container_CAN               | -0.052 | ***  |      0.001 |   0.000 |       -0.054 |       -0.050 |
| Beta: log_floz                    | -0.142 | ***  |      0.011 |   0.000 |       -0.163 |       -0.121 |
| Intercept                         | -2.123 | ***  |      0.012 |   0.000 |       -2.147 |       -2.098 |
----------------------------------------------------------------------------------------------------------
| Observations                      | 48,375 |      |            |         |              |              |
| R²                                |  0.553 |      |            |         |              |              |
| RMSE                              |  0.168 |      |            |         |              |              |
+-----------------------------------+--------+------+------------+---------+--------------+--------------+</code></pre>
</div>
</div>
</section>
<section id="model-2" class="level3">
<h3 class="anchored" data-anchor-id="model-2">Model 2</h3>
<div id="cell-20" class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>dtrain, dtest <span class="op">=</span> bm.randomSplit([<span class="fl">0.67</span>, <span class="fl">0.33</span>], seed <span class="op">=</span> <span class="dv">123</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-21" class="cell" data-outputid="756cab4d-c204-43b5-c3c4-330c9dcbe154">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>dtrain <span class="op">=</span> dtrain.withColumn(<span class="st">'log_floz'</span>, log(<span class="st">'beer_floz'</span>))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>dtrain <span class="op">=</span> dtrain.withColumn(<span class="st">'log_price_floz'</span>, log(<span class="st">'price_floz'</span>))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>dtest <span class="op">=</span> dtest.withColumn(<span class="st">'log_floz'</span>, log(<span class="st">'beer_floz'</span>))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>dtest <span class="op">=</span> dtest.withColumn(<span class="st">'log_price_floz'</span>, log(<span class="st">'price_floz'</span>))</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>dtrain.orderBy(<span class="st">'market'</span>, <span class="st">'brand'</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>dtest.orderBy(<span class="st">'market'</span>, <span class="st">'brand'</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>market_dummys, market_reflev <span class="op">=</span> add_dummy_variables(<span class="st">'market'</span>, reference_level<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>brand_dummys, brand_reflev <span class="op">=</span> add_dummy_variables(<span class="st">'brand'</span>, reference_level<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>container_dummys, container_reflev <span class="op">=</span> add_dummy_variables(<span class="st">'container'</span>, reference_level<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>cont <span class="op">=</span> [<span class="st">'log_floz'</span>]</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>features_2 <span class="op">=</span> market_dummys <span class="op">+</span> brand_dummys <span class="op">+</span> container_dummys <span class="op">+</span> cont</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reference category (dummy omitted): BUFFALO-ROCHESTER
Reference category (dummy omitted): BUD_LIGHT
Reference category (dummy omitted): NON_REFILLABLE_BOTTLE</code></pre>
</div>
</div>
<div id="cell-22" class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> brand_dummys:</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  dtrain <span class="op">=</span> dtrain.withColumn(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">_log_floz"</span>, col(i) <span class="op">*</span> col(<span class="st">'log_floz'</span>))</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  dtest <span class="op">=</span> dtest.withColumn(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">_log_floz"</span>, col(i) <span class="op">*</span> col(<span class="st">'log_floz'</span>))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  features_2.append(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">_log_floz"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-23" class="cell" data-outputid="ab2ffeb6-6829-49cd-a739-58fa7b74666a">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>assembler2 <span class="op">=</span> VectorAssembler(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    inputCols <span class="op">=</span> features_2,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    outputCol<span class="op">=</span><span class="st">'features'</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>dtrain2 <span class="op">=</span> assembler2.transform(dtrain)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>dtest2  <span class="op">=</span> assembler2.transform(dtest)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>model2 <span class="op">=</span> LinearRegression(</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    featuresCol<span class="op">=</span><span class="st">'features'</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    labelCol<span class="op">=</span><span class="st">'log_price_floz'</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>).fit(dtrain2)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>dtest2 <span class="op">=</span> model2.transform(dtest2)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(regression_table(model2, assembler2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>+------------------------------------+--------+------+------------+---------+--------------+--------------+
| Metric                             |  Value | Sig. | Std. Error | p-value | 95% CI Lower | 95% CI Upper |
+------------------------------------+--------+------+------------+---------+--------------+--------------+
| Beta: market_ALBANY                |  0.033 | ***  |      0.010 |   0.008 |        0.013 |        0.053 |
| Beta: market_ATLANTA               |  0.094 | ***  |      0.014 |   0.000 |        0.067 |        0.120 |
| Beta: market_BALTIMORE             |  0.101 | ***  |      0.010 |   0.000 |        0.081 |        0.122 |
| Beta: market_BIRMINGHAM            |  0.134 | ***  |      0.011 |   0.000 |        0.113 |        0.155 |
| Beta: market_BOSTON                |  0.128 | ***  |      0.010 |   0.000 |        0.108 |        0.148 |
| Beta: market_CHARLOTTE             |  0.029 | ***  |      0.010 |   0.005 |        0.010 |        0.048 |
| Beta: market_CHICAGO               | -0.008 |      |      0.010 |   0.407 |       -0.028 |        0.012 |
| Beta: market_CINCINNATI            |  0.083 | ***  |      0.010 |   0.000 |        0.063 |        0.103 |
| Beta: market_CLEVELAND             |  0.065 | ***  |      0.010 |   0.000 |        0.046 |        0.084 |
| Beta: market_COLUMBUS              |  0.074 | ***  |      0.010 |   0.000 |        0.055 |        0.093 |
| Beta: market_DALLAS                |  0.219 | ***  |      0.011 |   0.000 |        0.197 |        0.241 |
| Beta: market_DENVER                |  0.122 | ***  |      0.011 |   0.000 |        0.100 |        0.145 |
| Beta: market_DES_MOINES            |  0.139 | ***  |      0.010 |   0.000 |        0.120 |        0.158 |
| Beta: market_DETROIT               |  0.091 | ***  |      0.016 |   0.000 |        0.060 |        0.122 |
| Beta: market_EXURBAN_NJ            |  0.218 | ***  |      0.021 |   0.000 |        0.177 |        0.259 |
| Beta: market_EXURBAN_NY            |  0.134 | ***  |      0.011 |   0.000 |        0.112 |        0.156 |
| Beta: market_GRAND_RAPIDS          |  0.083 | ***  |      0.014 |   0.000 |        0.056 |        0.109 |
| Beta: market_HARTFORD-NEW_HAVEN    |  0.147 | ***  |      0.010 |   0.000 |        0.128 |        0.166 |
| Beta: market_HOUSTON               |  0.119 | ***  |      0.010 |   0.000 |        0.099 |        0.139 |
| Beta: market_INDIANAPOLIS          |  0.050 | ***  |      0.012 |   0.000 |        0.026 |        0.074 |
| Beta: market_JACKSONVILLE          |  0.123 | ***  |      0.012 |   0.000 |        0.100 |        0.145 |
| Beta: market_KANSAS_CITY           |  0.079 | ***  |      0.013 |   0.000 |        0.054 |        0.104 |
| Beta: market_LITTLE_ROCK           |  0.104 | ***  |      0.010 |   0.000 |        0.085 |        0.123 |
| Beta: market_LOS_ANGELES           |  0.026 | ***  |      0.011 |   0.009 |        0.004 |        0.047 |
| Beta: market_LOUISVILLE            |  0.065 | ***  |      0.012 |   0.000 |        0.041 |        0.088 |
| Beta: market_MEMPHIS               |  0.128 | ***  |      0.009 |   0.000 |        0.109 |        0.146 |
| Beta: market_MIAMI                 |  0.114 | ***  |      0.011 |   0.000 |        0.091 |        0.136 |
| Beta: market_MILWAUKEE             |  0.038 | ***  |      0.011 |   0.001 |        0.016 |        0.060 |
| Beta: market_MINNEAPOLIS           |  0.135 | ***  |      0.011 |   0.000 |        0.115 |        0.156 |
| Beta: market_NASHVILLE             |  0.145 | ***  |      0.011 |   0.000 |        0.124 |        0.167 |
| Beta: market_NEW_ORLEANS-MOBILE    |  0.127 | ***  |      0.011 |   0.000 |        0.105 |        0.149 |
| Beta: market_OKLAHOMA_CITY-TULSA   |  0.147 | ***  |      0.011 |   0.000 |        0.126 |        0.168 |
| Beta: market_OMAHA                 |  0.127 | ***  |      0.010 |   0.000 |        0.106 |        0.147 |
| Beta: market_ORLANDO               |  0.107 | ***  |      0.013 |   0.000 |        0.081 |        0.132 |
| Beta: market_PHILADELPHIA          |  0.124 | ***  |      0.009 |   0.000 |        0.106 |        0.142 |
| Beta: market_PHOENIX               |  0.148 | ***  |      0.014 |   0.000 |        0.121 |        0.175 |
| Beta: market_PITTSBURGH            |  0.098 | ***  |      0.012 |   0.000 |        0.074 |        0.121 |
| Beta: market_PORTLAND              |  0.107 | ***  |      0.010 |   0.000 |        0.086 |        0.127 |
| Beta: market_RALEIGH-DURHAM        |  0.087 | ***  |      0.011 |   0.000 |        0.066 |        0.107 |
| Beta: market_RICHMOND              |  0.041 | ***  |      0.014 |   0.000 |        0.013 |        0.069 |
| Beta: market_RURAL_ALABAMA         |  0.164 | ***  |      0.018 |   0.000 |        0.128 |        0.200 |
| Beta: market_RURAL_ARKANSAS        |  0.191 | ***  |      0.011 |   0.000 |        0.169 |        0.212 |
| Beta: market_RURAL_CALIFORNIA      |  0.044 | ***  |      0.047 |   0.000 |       -0.048 |        0.136 |
| Beta: market_RURAL_COLORADO        |  0.195 | ***  |      0.012 |   0.000 |        0.171 |        0.219 |
| Beta: market_RURAL_FLORIDA         |  0.061 | ***  |      0.013 |   0.000 |        0.036 |        0.086 |
| Beta: market_RURAL_GEORGIA         |  0.133 | ***  |      0.019 |   0.000 |        0.097 |        0.170 |
| Beta: market_RURAL_IDAHO           |  0.139 | ***  |      0.010 |   0.000 |        0.119 |        0.159 |
| Beta: market_RURAL_ILLINOIS        |  0.017 |      |      0.013 |   0.106 |       -0.008 |        0.041 |
| Beta: market_RURAL_INDIANA         |  0.071 | ***  |      0.010 |   0.000 |        0.050 |        0.091 |
| Beta: market_RURAL_IOWA            |  0.057 | ***  |      0.018 |   0.000 |        0.021 |        0.092 |
| Beta: market_RURAL_KANSAS          |  0.141 | ***  |      0.016 |   0.000 |        0.109 |        0.173 |
| Beta: market_RURAL_KENTUCKY        |  0.151 | ***  |      0.013 |   0.000 |        0.125 |        0.177 |
| Beta: market_RURAL_LOUISIANA       |  0.073 | ***  |      0.014 |   0.000 |        0.046 |        0.100 |
| Beta: market_RURAL_MAINE           |  0.087 | ***  |      0.011 |   0.000 |        0.064 |        0.109 |
| Beta: market_RURAL_MICHIGAN        |  0.085 | ***  |      0.019 |   0.000 |        0.048 |        0.123 |
| Beta: market_RURAL_MINNESOTA       |  0.177 | ***  |      0.014 |   0.000 |        0.150 |        0.204 |
| Beta: market_RURAL_MISSISSIPPI     |  0.048 | ***  |      0.012 |   0.001 |        0.025 |        0.071 |
| Beta: market_RURAL_MISSOURI        |  0.109 | ***  |      0.013 |   0.000 |        0.083 |        0.135 |
| Beta: market_RURAL_MONTANA         |  0.126 | ***  |      0.021 |   0.000 |        0.084 |        0.168 |
| Beta: market_RURAL_NEBRASKA        |  0.147 | ***  |      0.012 |   0.000 |        0.124 |        0.171 |
| Beta: market_RURAL_NEVADA          |  0.046 | ***  |      0.040 |   0.000 |       -0.033 |        0.125 |
| Beta: market_RURAL_NEW_HAMPSHIRE   |  0.054 |      |      0.013 |   0.177 |        0.028 |        0.080 |
| Beta: market_RURAL_NEW_MEXICO      |  0.163 | ***  |      0.064 |   0.000 |        0.038 |        0.287 |
| Beta: market_RURAL_NEW_YORK        | -0.007 |      |      0.011 |   0.914 |       -0.029 |        0.015 |
| Beta: market_RURAL_NORTH_CAROLINA  |  0.056 | ***  |      0.020 |   0.000 |        0.017 |        0.094 |
| Beta: market_RURAL_NORTH_DAKOTA    |  0.243 | ***  |      0.016 |   0.000 |        0.213 |        0.274 |
| Beta: market_RURAL_OHIO            |  0.093 | ***  |      0.029 |   0.000 |        0.036 |        0.149 |
| Beta: market_RURAL_OKLAHOMA        |  0.158 | ***  |      0.037 |   0.000 |        0.087 |        0.230 |
| Beta: market_RURAL_OREGON          |  0.002 |      |      0.014 |   0.962 |       -0.026 |        0.030 |
| Beta: market_RURAL_PENNSYLVANIA    |  0.136 | ***  |      0.010 |   0.000 |        0.116 |        0.156 |
| Beta: market_RURAL_SOUTH_CAROLINA  |  0.055 | ***  |      0.018 |   0.000 |        0.019 |        0.091 |
| Beta: market_RURAL_SOUTH_DAKOTA    |  0.083 | ***  |      0.013 |   0.000 |        0.057 |        0.108 |
| Beta: market_RURAL_TENNESSEE       |  0.176 | ***  |      0.010 |   0.000 |        0.157 |        0.195 |
| Beta: market_RURAL_TEXAS           |  0.176 | ***  |      0.020 |   0.000 |        0.137 |        0.215 |
| Beta: market_RURAL_VERMONT         |  0.079 | ***  |      0.017 |   0.000 |        0.046 |        0.112 |
| Beta: market_RURAL_VIRGINIA        |  0.014 |      |      0.014 |   0.408 |       -0.013 |        0.041 |
| Beta: market_RURAL_WASHINGTON      |  0.098 | ***  |      0.015 |   0.000 |        0.069 |        0.128 |
| Beta: market_RURAL_WEST_VIRGINIA   | -0.037 |  **  |      0.010 |   0.014 |       -0.057 |       -0.017 |
| Beta: market_RURAL_WISCONSIN       |  0.047 | ***  |      0.033 |   0.000 |       -0.019 |        0.112 |
| Beta: market_RURAL_WYOMING         |  0.150 | ***  |      0.011 |   0.000 |        0.129 |        0.171 |
| Beta: market_SACRAMENTO            |  0.030 | ***  |      0.014 |   0.004 |        0.003 |        0.058 |
| Beta: market_SALT_LAKE_CITY        |  0.113 | ***  |      0.009 |   0.000 |        0.095 |        0.131 |
| Beta: market_SAN_ANTONIO           |  0.140 | ***  |      0.012 |   0.000 |        0.118 |        0.163 |
| Beta: market_SAN_DIEGO             |  0.017 |      |      0.011 |   0.142 |       -0.004 |        0.038 |
| Beta: market_SAN_FRANCISCO         |  0.076 | ***  |      0.011 |   0.000 |        0.055 |        0.097 |
| Beta: market_SEATTLE               |  0.105 | ***  |      0.010 |   0.000 |        0.086 |        0.125 |
| Beta: market_ST_LOUIS              |  0.038 | ***  |      0.013 |   0.000 |        0.012 |        0.064 |
| Beta: market_SURBURBAN_NJ          | -0.021 |      |      0.013 |   0.109 |       -0.046 |        0.004 |
| Beta: market_SURBURBAN_NY          |  0.104 | ***  |      0.014 |   0.000 |        0.076 |        0.132 |
| Beta: market_SYRACUSE              | -0.038 | ***  |      0.009 |   0.007 |       -0.056 |       -0.020 |
| Beta: market_TAMPA                 |  0.108 | ***  |      0.011 |   0.000 |        0.086 |        0.130 |
| Beta: market_URBAN_NY              |  0.172 | ***  |      0.011 |   0.000 |        0.150 |        0.193 |
| Beta: market_WASHINGTON_DC         |  0.101 | ***  |      0.022 |   0.000 |        0.058 |        0.144 |
| Beta: brand_BUSCH_LIGHT            | -0.228 | ***  |      0.018 |   0.000 |       -0.264 |       -0.192 |
| Beta: brand_COORS_LIGHT            |  0.013 |      |      0.017 |   0.481 |       -0.019 |        0.045 |
| Beta: brand_MILLER_LITE            |  0.067 | ***  |      0.017 |   0.000 |        0.033 |        0.101 |
| Beta: brand_NATURAL_LIGHT          | -0.595 | ***  |      0.002 |   0.000 |       -0.599 |       -0.592 |
| Beta: container_CAN                | -0.051 | ***  |      0.002 |   0.000 |       -0.055 |       -0.047 |
| Beta: log_floz                     | -0.148 | ***  |      0.004 |   0.000 |       -0.156 |       -0.140 |
| Beta: brand_BUSCH_LIGHT_log_floz   | -0.006 |      |      0.003 |   0.156 |       -0.012 |        0.001 |
| Beta: brand_COORS_LIGHT_log_floz   | -0.003 |      |      0.003 |   0.396 |       -0.009 |        0.003 |
| Beta: brand_MILLER_LITE_log_floz   | -0.015 | ***  |      0.003 |   0.000 |       -0.021 |       -0.009 |
| Beta: brand_NATURAL_LIGHT_log_floz |  0.051 | ***  |      0.014 |   0.000 |        0.024 |        0.079 |
| Intercept                          | -2.089 | ***  |      0.012 |   0.000 |       -2.113 |       -2.064 |
-----------------------------------------------------------------------------------------------------------
| Observations                       | 48,375 |      |            |         |              |              |
| R²                                 |  0.558 |      |            |         |              |              |
| RMSE                               |  0.167 |      |            |         |              |              |
+------------------------------------+--------+------+------------+---------+--------------+--------------+</code></pre>
</div>
</div>
</section>
<section id="model-3" class="level3">
<h3 class="anchored" data-anchor-id="model-3">Model 3</h3>
<div id="cell-25" class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>dtrain, dtest <span class="op">=</span> bm.randomSplit([<span class="fl">0.67</span>, <span class="fl">0.33</span>], seed <span class="op">=</span> <span class="dv">123</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-26" class="cell" data-outputid="f9c25207-1193-4922-c5a1-0baee9e4bc6e">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>dtrain <span class="op">=</span> dtrain.withColumn(<span class="st">'log_floz'</span>, log(<span class="st">'beer_floz'</span>))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>dtrain <span class="op">=</span> dtrain.withColumn(<span class="st">'log_price_floz'</span>, log(<span class="st">'price_floz'</span>))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>dtest <span class="op">=</span> dtest.withColumn(<span class="st">'log_floz'</span>, log(<span class="st">'beer_floz'</span>))</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>dtest <span class="op">=</span> dtest.withColumn(<span class="st">'log_price_floz'</span>, log(<span class="st">'price_floz'</span>))</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>dtrain.orderBy(<span class="st">'market'</span>, <span class="st">'brand'</span>)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>dtest.orderBy(<span class="st">'market'</span>, <span class="st">'brand'</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>market_dummys, market_reflev <span class="op">=</span> add_dummy_variables(<span class="st">'market'</span>, reference_level<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>brand_dummys, brand_reflev <span class="op">=</span> add_dummy_variables(<span class="st">'brand'</span>, reference_level<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>container_dummys, container_reflev <span class="op">=</span> add_dummy_variables(<span class="st">'container'</span>, reference_level<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>cont <span class="op">=</span> [<span class="st">'log_floz'</span>]</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>features_3 <span class="op">=</span> market_dummys <span class="op">+</span> brand_dummys <span class="op">+</span> container_dummys <span class="op">+</span> cont</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reference category (dummy omitted): BUFFALO-ROCHESTER
Reference category (dummy omitted): BUD_LIGHT
Reference category (dummy omitted): NON_REFILLABLE_BOTTLE</code></pre>
</div>
</div>
<div id="cell-27" class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>dtrain <span class="op">=</span> dtrain.withColumn(<span class="st">'promo_x_log_floz'</span>, col(<span class="st">'promo'</span>).cast(<span class="st">'int'</span>) <span class="op">*</span> col(<span class="st">'log_floz'</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>dtest <span class="op">=</span> dtest.withColumn(<span class="st">'promo_x_log_floz'</span>, col(<span class="st">'promo'</span>).cast(<span class="st">'int'</span>) <span class="op">*</span> col(<span class="st">'log_floz'</span>))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>features_3.append(<span class="st">'promo_x_log_floz'</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> brand_dummys:</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  dtrain <span class="op">=</span> dtrain.withColumn(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">_log_floz"</span>, col(i) <span class="op">*</span> col(<span class="st">'log_floz'</span>))</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  dtest <span class="op">=</span> dtest.withColumn(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">_log_floz"</span>, col(i) <span class="op">*</span> col(<span class="st">'log_floz'</span>))</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  dtrain <span class="op">=</span> dtrain.withColumn(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">_promo"</span>, col(i) <span class="op">*</span> col(<span class="st">'promo'</span>).cast(<span class="st">'int'</span>))</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  dtest <span class="op">=</span> dtest.withColumn(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">_promo"</span>, col(i) <span class="op">*</span> col(<span class="st">'promo'</span>).cast(<span class="st">'int'</span>))</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  dtrain <span class="op">=</span> dtrain.withColumn(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">_promo_log_floz"</span>, col(i) <span class="op">*</span> col(<span class="st">'promo'</span>).cast(<span class="st">'int'</span>) <span class="op">*</span> col(<span class="st">'log_floz'</span>))</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  dtest <span class="op">=</span> dtest.withColumn(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">_promo_log_floz"</span>, col(i) <span class="op">*</span> col(<span class="st">'promo'</span>).cast(<span class="st">'int'</span>) <span class="op">*</span> col(<span class="st">'log_floz'</span>))</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  features_3.append(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">_log_floz"</span>)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  features_3.append(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">_promo"</span>)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  features_3.append(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">_promo_log_floz"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-28" class="cell" data-outputid="ddbda90a-2e18-4019-995d-c3dc1d00c1ed">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>assembler3 <span class="op">=</span> VectorAssembler(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    inputCols <span class="op">=</span> features_3,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    outputCol<span class="op">=</span><span class="st">'features'</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>dtrain3 <span class="op">=</span> assembler3.transform(dtrain)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>dtest3  <span class="op">=</span> assembler3.transform(dtest)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>model3 <span class="op">=</span> LinearRegression(</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    featuresCol<span class="op">=</span><span class="st">'features'</span>,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    labelCol<span class="op">=</span><span class="st">'log_price_floz'</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>).fit(dtrain3)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>dtest3 <span class="op">=</span> model3.transform(dtest3)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(regression_table(model3, assembler3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>+------------------------------------------+--------+------+------------+---------+--------------+--------------+
| Metric                                   |  Value | Sig. | Std. Error | p-value | 95% CI Lower | 95% CI Upper |
+------------------------------------------+--------+------+------------+---------+--------------+--------------+
| Beta: market_ALBANY                      |  0.027 |  **  |      0.010 |   0.029 |        0.007 |        0.047 |
| Beta: market_ATLANTA                     |  0.090 | ***  |      0.014 |   0.000 |        0.063 |        0.117 |
| Beta: market_BALTIMORE                   |  0.092 | ***  |      0.010 |   0.000 |        0.072 |        0.112 |
| Beta: market_BIRMINGHAM                  |  0.130 | ***  |      0.011 |   0.000 |        0.109 |        0.151 |
| Beta: market_BOSTON                      |  0.126 | ***  |      0.010 |   0.000 |        0.106 |        0.146 |
| Beta: market_CHARLOTTE                   |  0.038 | ***  |      0.010 |   0.000 |        0.019 |        0.057 |
| Beta: market_CHICAGO                     | -0.002 |      |      0.010 |   0.832 |       -0.022 |        0.018 |
| Beta: market_CINCINNATI                  |  0.082 | ***  |      0.010 |   0.000 |        0.062 |        0.102 |
| Beta: market_CLEVELAND                   |  0.062 | ***  |      0.010 |   0.000 |        0.043 |        0.080 |
| Beta: market_COLUMBUS                    |  0.074 | ***  |      0.009 |   0.000 |        0.056 |        0.093 |
| Beta: market_DALLAS                      |  0.223 | ***  |      0.011 |   0.000 |        0.202 |        0.245 |
| Beta: market_DENVER                      |  0.134 | ***  |      0.011 |   0.000 |        0.112 |        0.157 |
| Beta: market_DES_MOINES                  |  0.133 | ***  |      0.010 |   0.000 |        0.114 |        0.151 |
| Beta: market_DETROIT                     |  0.093 | ***  |      0.016 |   0.000 |        0.062 |        0.124 |
| Beta: market_EXURBAN_NJ                  |  0.210 | ***  |      0.021 |   0.000 |        0.169 |        0.251 |
| Beta: market_EXURBAN_NY                  |  0.128 | ***  |      0.011 |   0.000 |        0.106 |        0.150 |
| Beta: market_GRAND_RAPIDS                |  0.081 | ***  |      0.013 |   0.000 |        0.055 |        0.108 |
| Beta: market_HARTFORD-NEW_HAVEN          |  0.144 | ***  |      0.010 |   0.000 |        0.125 |        0.163 |
| Beta: market_HOUSTON                     |  0.122 | ***  |      0.010 |   0.000 |        0.102 |        0.142 |
| Beta: market_INDIANAPOLIS                |  0.051 | ***  |      0.012 |   0.000 |        0.027 |        0.075 |
| Beta: market_JACKSONVILLE                |  0.124 | ***  |      0.012 |   0.000 |        0.101 |        0.147 |
| Beta: market_KANSAS_CITY                 |  0.074 | ***  |      0.013 |   0.000 |        0.049 |        0.100 |
| Beta: market_LITTLE_ROCK                 |  0.100 | ***  |      0.010 |   0.000 |        0.080 |        0.119 |
| Beta: market_LOS_ANGELES                 |  0.034 | ***  |      0.011 |   0.000 |        0.013 |        0.055 |
| Beta: market_LOUISVILLE                  |  0.069 | ***  |      0.012 |   0.000 |        0.046 |        0.093 |
| Beta: market_MEMPHIS                     |  0.122 | ***  |      0.009 |   0.000 |        0.103 |        0.140 |
| Beta: market_MIAMI                       |  0.115 | ***  |      0.011 |   0.000 |        0.093 |        0.137 |
| Beta: market_MILWAUKEE                   |  0.040 | ***  |      0.011 |   0.000 |        0.019 |        0.062 |
| Beta: market_MINNEAPOLIS                 |  0.131 | ***  |      0.011 |   0.000 |        0.111 |        0.152 |
| Beta: market_NASHVILLE                   |  0.144 | ***  |      0.011 |   0.000 |        0.123 |        0.166 |
| Beta: market_NEW_ORLEANS-MOBILE          |  0.122 | ***  |      0.011 |   0.000 |        0.101 |        0.144 |
| Beta: market_OKLAHOMA_CITY-TULSA         |  0.140 | ***  |      0.010 |   0.000 |        0.120 |        0.161 |
| Beta: market_OMAHA                       |  0.129 | ***  |      0.010 |   0.000 |        0.108 |        0.149 |
| Beta: market_ORLANDO                     |  0.109 | ***  |      0.013 |   0.000 |        0.084 |        0.134 |
| Beta: market_PHILADELPHIA                |  0.113 | ***  |      0.009 |   0.000 |        0.095 |        0.132 |
| Beta: market_PHOENIX                     |  0.156 | ***  |      0.014 |   0.000 |        0.129 |        0.183 |
| Beta: market_PITTSBURGH                  |  0.093 | ***  |      0.012 |   0.000 |        0.070 |        0.117 |
| Beta: market_PORTLAND                    |  0.109 | ***  |      0.010 |   0.000 |        0.089 |        0.130 |
| Beta: market_RALEIGH-DURHAM              |  0.082 | ***  |      0.010 |   0.000 |        0.062 |        0.103 |
| Beta: market_RICHMOND                    |  0.036 | ***  |      0.014 |   0.001 |        0.008 |        0.064 |
| Beta: market_RURAL_ALABAMA               |  0.159 | ***  |      0.018 |   0.000 |        0.124 |        0.195 |
| Beta: market_RURAL_ARKANSAS              |  0.183 | ***  |      0.011 |   0.000 |        0.162 |        0.205 |
| Beta: market_RURAL_CALIFORNIA            |  0.047 | ***  |      0.047 |   0.000 |       -0.045 |        0.138 |
| Beta: market_RURAL_COLORADO              |  0.194 | ***  |      0.012 |   0.000 |        0.170 |        0.218 |
| Beta: market_RURAL_FLORIDA               |  0.060 | ***  |      0.013 |   0.000 |        0.036 |        0.085 |
| Beta: market_RURAL_GEORGIA               |  0.129 | ***  |      0.019 |   0.000 |        0.092 |        0.165 |
| Beta: market_RURAL_IDAHO                 |  0.139 | ***  |      0.010 |   0.000 |        0.119 |        0.159 |
| Beta: market_RURAL_ILLINOIS              |  0.015 |      |      0.012 |   0.147 |       -0.010 |        0.039 |
| Beta: market_RURAL_INDIANA               |  0.072 | ***  |      0.010 |   0.000 |        0.051 |        0.092 |
| Beta: market_RURAL_IOWA                  |  0.054 | ***  |      0.018 |   0.000 |        0.018 |        0.089 |
| Beta: market_RURAL_KANSAS                |  0.133 | ***  |      0.016 |   0.000 |        0.101 |        0.165 |
| Beta: market_RURAL_KENTUCKY              |  0.148 | ***  |      0.013 |   0.000 |        0.123 |        0.174 |
| Beta: market_RURAL_LOUISIANA             |  0.065 | ***  |      0.014 |   0.000 |        0.038 |        0.091 |
| Beta: market_RURAL_MAINE                 |  0.085 | ***  |      0.011 |   0.000 |        0.063 |        0.107 |
| Beta: market_RURAL_MICHIGAN              |  0.081 | ***  |      0.019 |   0.000 |        0.044 |        0.118 |
| Beta: market_RURAL_MINNESOTA             |  0.171 | ***  |      0.014 |   0.000 |        0.144 |        0.198 |
| Beta: market_RURAL_MISSISSIPPI           |  0.049 | ***  |      0.012 |   0.000 |        0.026 |        0.071 |
| Beta: market_RURAL_MISSOURI              |  0.102 | ***  |      0.013 |   0.000 |        0.076 |        0.128 |
| Beta: market_RURAL_MONTANA               |  0.133 | ***  |      0.021 |   0.000 |        0.092 |        0.175 |
| Beta: market_RURAL_NEBRASKA              |  0.144 | ***  |      0.012 |   0.000 |        0.121 |        0.168 |
| Beta: market_RURAL_NEVADA                |  0.045 | ***  |      0.040 |   0.000 |       -0.034 |        0.123 |
| Beta: market_RURAL_NEW_HAMPSHIRE         |  0.049 |      |      0.013 |   0.219 |        0.023 |        0.075 |
| Beta: market_RURAL_NEW_MEXICO            |  0.160 | ***  |      0.063 |   0.000 |        0.036 |        0.284 |
| Beta: market_RURAL_NEW_YORK              | -0.020 |      |      0.011 |   0.757 |       -0.041 |        0.002 |
| Beta: market_RURAL_NORTH_CAROLINA        |  0.044 | ***  |      0.019 |   0.000 |        0.006 |        0.083 |
| Beta: market_RURAL_NORTH_DAKOTA          |  0.243 | ***  |      0.016 |   0.000 |        0.212 |        0.274 |
| Beta: market_RURAL_OHIO                  |  0.090 | ***  |      0.028 |   0.000 |        0.034 |        0.146 |
| Beta: market_RURAL_OKLAHOMA              |  0.147 | ***  |      0.036 |   0.000 |        0.076 |        0.219 |
| Beta: market_RURAL_OREGON                |  0.006 |      |      0.014 |   0.874 |       -0.022 |        0.034 |
| Beta: market_RURAL_PENNSYLVANIA          |  0.127 | ***  |      0.010 |   0.000 |        0.107 |        0.147 |
| Beta: market_RURAL_SOUTH_CAROLINA        |  0.058 | ***  |      0.018 |   0.000 |        0.023 |        0.094 |
| Beta: market_RURAL_SOUTH_DAKOTA          |  0.079 | ***  |      0.013 |   0.000 |        0.054 |        0.105 |
| Beta: market_RURAL_TENNESSEE             |  0.179 | ***  |      0.010 |   0.000 |        0.160 |        0.198 |
| Beta: market_RURAL_TEXAS                 |  0.173 | ***  |      0.020 |   0.000 |        0.135 |        0.212 |
| Beta: market_RURAL_VERMONT               |  0.079 | ***  |      0.017 |   0.000 |        0.046 |        0.112 |
| Beta: market_RURAL_VIRGINIA              |  0.011 |      |      0.014 |   0.523 |       -0.016 |        0.038 |
| Beta: market_RURAL_WASHINGTON            |  0.115 | ***  |      0.015 |   0.000 |        0.086 |        0.144 |
| Beta: market_RURAL_WEST_VIRGINIA         | -0.045 | ***  |      0.010 |   0.003 |       -0.065 |       -0.025 |
| Beta: market_RURAL_WISCONSIN             |  0.046 | ***  |      0.033 |   0.000 |       -0.018 |        0.111 |
| Beta: market_RURAL_WYOMING               |  0.144 | ***  |      0.011 |   0.000 |        0.123 |        0.164 |
| Beta: market_SACRAMENTO                  |  0.038 | ***  |      0.014 |   0.000 |        0.011 |        0.066 |
| Beta: market_SALT_LAKE_CITY              |  0.112 | ***  |      0.009 |   0.000 |        0.094 |        0.130 |
| Beta: market_SAN_ANTONIO                 |  0.138 | ***  |      0.011 |   0.000 |        0.115 |        0.160 |
| Beta: market_SAN_DIEGO                   |  0.022 |  *   |      0.011 |   0.060 |        0.000 |        0.043 |
| Beta: market_SAN_FRANCISCO               |  0.082 | ***  |      0.011 |   0.000 |        0.061 |        0.103 |
| Beta: market_SEATTLE                     |  0.118 | ***  |      0.010 |   0.000 |        0.098 |        0.137 |
| Beta: market_ST_LOUIS                    |  0.042 | ***  |      0.013 |   0.000 |        0.016 |        0.067 |
| Beta: market_SURBURBAN_NJ                | -0.031 |  **  |      0.012 |   0.018 |       -0.055 |       -0.006 |
| Beta: market_SURBURBAN_NY                |  0.104 | ***  |      0.014 |   0.000 |        0.076 |        0.132 |
| Beta: market_SYRACUSE                    | -0.046 | ***  |      0.009 |   0.001 |       -0.064 |       -0.028 |
| Beta: market_TAMPA                       |  0.109 | ***  |      0.011 |   0.000 |        0.088 |        0.131 |
| Beta: market_URBAN_NY                    |  0.170 | ***  |      0.011 |   0.000 |        0.148 |        0.191 |
| Beta: market_WASHINGTON_DC               |  0.096 | ***  |      0.023 |   0.000 |        0.051 |        0.141 |
| Beta: brand_BUSCH_LIGHT                  | -0.183 | ***  |      0.019 |   0.000 |       -0.221 |       -0.146 |
| Beta: brand_COORS_LIGHT                  |  0.033 |  *   |      0.017 |   0.088 |       -0.001 |        0.066 |
| Beta: brand_MILLER_LITE                  |  0.105 | ***  |      0.018 |   0.000 |        0.069 |        0.141 |
| Beta: brand_NATURAL_LIGHT                | -0.522 | ***  |      0.002 |   0.000 |       -0.526 |       -0.518 |
| Beta: container_CAN                      | -0.052 | ***  |      0.002 |   0.000 |       -0.056 |       -0.048 |
| Beta: log_floz                           | -0.143 | ***  |      0.001 |   0.000 |       -0.144 |       -0.141 |
| Beta: promo_x_log_floz                   | -0.008 | ***  |      0.004 |   0.000 |       -0.016 |       -0.000 |
| Beta: brand_BUSCH_LIGHT_log_floz         | -0.014 | ***  |      0.059 |   0.001 |       -0.129 |        0.100 |
| Beta: brand_BUSCH_LIGHT_promo            | -0.297 | ***  |      0.010 |   0.000 |       -0.317 |       -0.277 |
| Beta: brand_BUSCH_LIGHT_promo_log_floz   |  0.054 | ***  |      0.004 |   0.000 |        0.047 |        0.061 |
| Beta: brand_COORS_LIGHT_log_floz         | -0.006 |  *   |      0.044 |   0.098 |       -0.093 |        0.081 |
| Beta: brand_COORS_LIGHT_promo            | -0.206 | ***  |      0.008 |   0.000 |       -0.222 |       -0.191 |
| Beta: brand_COORS_LIGHT_promo_log_floz   |  0.034 | ***  |      0.003 |   0.000 |        0.028 |        0.040 |
| Beta: brand_MILLER_LITE_log_floz         | -0.022 | ***  |      0.035 |   0.000 |       -0.092 |        0.047 |
| Beta: brand_MILLER_LITE_promo            | -0.311 | ***  |      0.006 |   0.000 |       -0.323 |       -0.298 |
| Beta: brand_MILLER_LITE_promo_log_floz   |  0.057 | ***  |      0.003 |   0.000 |        0.050 |        0.063 |
| Beta: brand_NATURAL_LIGHT_log_floz       |  0.038 | ***  |      0.034 |   0.000 |       -0.030 |        0.105 |
| Beta: brand_NATURAL_LIGHT_promo          | -0.365 | ***  |      0.006 |   0.000 |       -0.377 |       -0.353 |
| Beta: brand_NATURAL_LIGHT_promo_log_floz |  0.065 | ***  |      0.014 |   0.000 |        0.037 |        0.092 |
| Intercept                                | -2.108 | ***  |      0.012 |   0.000 |       -2.132 |       -2.084 |
-----------------------------------------------------------------------------------------------------------------
| Observations                             | 48,375 |      |            |         |              |              |
| R²                                       |  0.565 |      |            |         |              |              |
| RMSE                                     |  0.165 |      |            |         |              |              |
+------------------------------------------+--------+------+------------+---------+--------------+--------------+</code></pre>
</div>
</div>
</section>
</section>
<section id="q5" class="level2">
<h2 class="anchored" data-anchor-id="q5">Q5</h2>
<blockquote class="blockquote">
<p><code>market_ALBANY</code>: 0.027 - Being in the Albany mkt leads to a 2.7% increase in log(price per fl oz)</p>
</blockquote>
<blockquote class="blockquote">
<p><code>market_EXURBAN_NY</code>: 0.128 - EXURBAN market leads to a larger 12.8% increase in log(price per fl oz)</p>
</blockquote>
<blockquote class="blockquote">
<p><code>market_RURAL_NEW_YORK</code>: -0.020 - Rural NY actually leads to a 2% decrease in log(price per fl oz)</p>
</blockquote>
<blockquote class="blockquote">
<p><code>market_SUBURBAN_NY</code>: 0.104 - Suburban NY leads to a 10.4% increase</p>
</blockquote>
<blockquote class="blockquote">
<p><code>market_SYRACUSE</code>: -0.046 - Syracuse leads to a 4.6% decrease</p>
</blockquote>
<blockquote class="blockquote">
<p><code>market_URBAN_NY</code>: 0.170 - Urban NY leads to a 17% increase</p>
</blockquote>
</section>
<section id="q6" class="level2">
<h2 class="anchored" data-anchor-id="q6">Q6</h2>
<blockquote class="blockquote">
<p>Betas Associated with log(beer_floz) - <code>model 1</code>: -0.142 - <code>model 2</code>: -0.148 - <code>model 3</code>: -0.143</p>
</blockquote>
<ul>
<li>Betas are actually quite similar across the models, with an average of ~ -0.144</li>
</ul>
<blockquote class="blockquote">
<p>How did promo affect this in model 3? - beta associated with the interaction: - <code>-0.008</code> - this interaction led to a decreased sensitivity</p>
</blockquote>
</section>
<section id="q7" class="level2">
<h2 class="anchored" data-anchor-id="q7">Q7</h2>
<div id="cell-34" class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="model-1-1" class="level3">
<h3 class="anchored" data-anchor-id="model-1-1">Model 1</h3>
<div id="cell-36" class="cell" data-outputid="996457fe-fcb3-463d-b67d-a862fa2b5df9">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>res_1 <span class="op">=</span> dtest1.select([<span class="st">"prediction"</span>, <span class="st">"log_price_floz"</span>]).toPandas()</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>res_1[<span class="st">'residual'</span>] <span class="op">=</span> res_1[<span class="st">'log_price_floz'</span>] <span class="op">-</span> res_1[<span class="st">'prediction'</span>]</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>plt.scatter(res_1[<span class="st">"prediction"</span>], res_1[<span class="st">"residual"</span>], alpha<span class="op">=</span><span class="fl">0.2</span>, color<span class="op">=</span><span class="st">"darkgray"</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>smoothed <span class="op">=</span> sm.nonparametric.lowess(res_1[<span class="st">"residual"</span>], res_1[<span class="st">"prediction"</span>])</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>plt.plot(smoothed[:, <span class="dv">0</span>], smoothed[:, <span class="dv">1</span>], color<span class="op">=</span><span class="st">"darkblue"</span>)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">"red"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Predicted log(price_floz) (Model 1)"</span>)</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Residuals"</span>)</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Residual Plot for Model 1"</span>)</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="danl_320_hw2_noone_daniel_files/figure-html/cell-21-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="model-2-1" class="level3">
<h3 class="anchored" data-anchor-id="model-2-1">Model 2</h3>
<div id="cell-38" class="cell" data-outputid="cd25eff4-b991-4cdc-c6cc-38b4b40f47a8">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>res_2 <span class="op">=</span> dtest2.select([<span class="st">"prediction"</span>, <span class="st">"log_price_floz"</span>]).toPandas()</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>res_2[<span class="st">'residual'</span>] <span class="op">=</span> res_2[<span class="st">'log_price_floz'</span>] <span class="op">-</span> res_2[<span class="st">'prediction'</span>]</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>plt.scatter(res_2[<span class="st">"prediction"</span>], res_2[<span class="st">"residual"</span>], alpha<span class="op">=</span><span class="fl">0.2</span>, color<span class="op">=</span><span class="st">"darkgray"</span>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>smoothed <span class="op">=</span> sm.nonparametric.lowess(res_2[<span class="st">"residual"</span>], res_2[<span class="st">"prediction"</span>])</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>plt.plot(smoothed[:, <span class="dv">0</span>], smoothed[:, <span class="dv">1</span>], color<span class="op">=</span><span class="st">"darkblue"</span>)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">"red"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Predicted log(price_floz) (Model 2)"</span>)</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Residuals"</span>)</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Residual Plot for Model 2"</span>)</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="danl_320_hw2_noone_daniel_files/figure-html/cell-22-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="model-3-1" class="level3">
<h3 class="anchored" data-anchor-id="model-3-1">Model 3</h3>
<div id="cell-40" class="cell" data-outputid="d55c72c3-910a-43e4-b115-50e46849c356">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>res_3 <span class="op">=</span> dtest3.select([<span class="st">"prediction"</span>, <span class="st">"log_price_floz"</span>]).toPandas()</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>res_3[<span class="st">'residual'</span>] <span class="op">=</span> res_3[<span class="st">'log_price_floz'</span>] <span class="op">-</span> res_3[<span class="st">'prediction'</span>]</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>plt.scatter(res_3[<span class="st">"prediction"</span>], res_3[<span class="st">"residual"</span>], alpha<span class="op">=</span><span class="fl">0.2</span>, color<span class="op">=</span><span class="st">"darkgray"</span>)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>smoothed <span class="op">=</span> sm.nonparametric.lowess(res_3[<span class="st">"residual"</span>], res_3[<span class="st">"prediction"</span>])</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>plt.plot(smoothed[:, <span class="dv">0</span>], smoothed[:, <span class="dv">1</span>], color<span class="op">=</span><span class="st">"darkblue"</span>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">"red"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Predicted log(price_floz) (Model 3)"</span>)</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Residuals"</span>)</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Residual Plot for Model 3"</span>)</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="danl_320_hw2_noone_daniel_files/figure-html/cell-23-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>On average, the predictions tend to be relatively close to actual, shown by the points sticking relatively close to the horizontal 0 line.</li>
</ul>
</section>
</section>
<section id="q8" class="level2">
<h2 class="anchored" data-anchor-id="q8">Q8</h2>
<blockquote class="blockquote">
<p><strong>Model Choice</strong>: - I would most likely choose model 3, as it has the higest R2, and performs seemingly as well as the others on the unseen test set.</p>
</blockquote>


</section>
</section>

</main> <!-- /main -->
<script type="text/javascript" src="links.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Powered with GitHub, Quarto and Rstudio<br>© Daniel Noone, 2023</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>